### ISSUE TITLE
A must have software: XRDP

### ISSUE THREAD

**Issue by netroby** [helloSystem/hello#100]
Hello, I am new to Hello System. 
I am very interest with Hello System. 
I want to contribute.
For now ,we can not using HelloSystem as primary OS, But we can try it another Laptop and Virtual Box?
So we need a remote connection to This desktop.
XRDP is a free remote desktop solution. It's free, and easy to setup. no much more bug or shit in it.

So i guess shall we put it include the Hello System. 
Help user to make it works.

If this done. many user can gave Hello System a try , and worried nothing.
It's just open then works.

**Comment by probonopd** [comment]
欢迎好友

helloSystem uses the VNC protocol.
To make it secure, we are using a ssh tunnel for it.
You can activate it under

Applications -> Utilities -> Sharing -> Check the "Remote Login" box and the "Screen Sharing" box

You can then use [SSVNC](http://www.karlrunge.com/x11vnc/ssvnc.html) to access the machine over the local area network.

In SSVNC please do: 
* Under "VNC Host_Display" please enter: <IP Address>:0
* Options... -> Check the "Use SSH" box and the "Unix Username & Password" box
* Under "Unix Username" enter the username you have set when you installed helloSystem
* Under "Unix Password" enter the password you have set when you installed helloSystem

Does this work for you?

Does it have to be RDP or could you also use VNC?
If you need RDP, then you can install `xrdp` on helloSystem with:

```
sudo pkg install xrdp
```

But I have not tested it.

Please let me know how it works for you.
Happy testing!

**Comment by netroby** [comment]
thanks. i will try for it.

**Comment by netroby** [comment]
VNC works, your answer awesome, can be added into User Manual.
That's great

**Comment by rbreaves** [comment]
Are there not any key remapping issues under xrdp or vnc? I ran into such things myself, but if your approach is already based in x11 then perhaps it does not matter. Mine was based on remapping uinput though :/.

I am just now figuring out how to resolve the issues.. but it is ongoing still.
https://github.com/rbreaves/kinto/issues/693
https://github.com/LibVNC/x11vnc/issues/193
