### ISSUE TITLE
Feedback on Reddit

### ISSUE THREAD

**Issue by linuxhw** [helloSystem/hello#102]
Feedback for article ["helloSystem: Three-layer UX design philosophy for Simplicity and Power"](https://medium.com/@probonopd/hellosystem-three-layer-ux-design-philosophy-for-simplicity-and-power-37c95bf58398).

Here https://www.reddit.com/r/BSD/comments/kzr9ix/hellosystem_threelayer_ux_design_philosophy_for/gjqyu8c/?utm_source=reddit&utm_medium=web2x&context=3

>Level 0: If the keyboard language is known, defaulting to that language should happen. However, such feature should be configurable. Automatic preference changes are bad, I might have a foreign keyboard, but use it in ascii mode most of the time.
>
>If language is not known, you should default to whatever language was selected at install. Defaulting to ascii since it is the defacto standard.
>
>Level 1: I agree with this if you're making a lcd (lowest common denominator) wm. I believe what you show in the pictures is a little too spartan.
>
>Level 2: I disagree that KDE's GUI is "convoluted." It is more than what most users need, but it is less work than using CLI tool. It is much easier/less work to see all the options included in the KDE than to read pages and pages of man pages looking for arguments. Anyone too stupid to use KDE's config are going to be too stupid to use CLI. Most people are not messing with these configurations frequently enough to know the CLI arguments, so not having advanced gui is a waste of user time. And not wasting user's time is the most important thing.
>
>I do agree the pictured UI needs a cleanup, horizontal scrolls are a no-no.
>
>Layer 3: Pointless. Most people who can use source code won't be using this wm. And even if they do, they'll know where and how to find the source.
>
>In my opinion, your layer 2 should be an advanced gui, your layer 3 should spit you to cli... But do as you will.

**Comment by probonopd** [comment]
Thanks for the feedback. After some consideration, I respectfully disagree that putting the source code under the (power) user's fingertips is "pointless".
