### ISSUE TITLE
Going home (for documents, on-disk movies and so on)

### ISSUE THREAD

**Issue by grahamperrin** [helloSystem/hello#103]
With my 'Mac head' on, I think of Finder as the primary approach to going ~ home. For documents, and so on. 

Finder, far left in the dock. 

For the past few days I've been thinking about navigation in helloSystem. There's https://github.com/helloSystem/filer however: 

* its primary name is **Applications** – not where I'd expect to find documents and so on
* its icon is ambiguous. 

Today for example, it was described as a _menu_: 

![2021-01-19 20:05:34](https://user-images.githubusercontent.com/192271/105091807-4ee39a80-5a98-11eb-9e81-c12f9c2e5846.png)

– which is understandable, because the cog icon (like a hamburger icon) does sometimes indicate a menu, or preferences, or whatever; it's ambiguous. 

I'd like an omnipresent, quick method of going home that does not rely upon a dock https://github.com/helloSystem/Menu/issues/21 and does not begin with a requirement to bring the filer to foreground.

Yesterday I instinctively typed: 

<kbd>h</kbd><kbd>o</kbd>

– expecting to find Home through the Search menu, I guess that this falls under the umbrella of https://github.com/helloSystem/Menu/issues/9

**Comment by probonopd** [comment]
We now have __Home__ as the first icon.

![image](https://user-images.githubusercontent.com/2480569/105615552-d51e1a80-5dd1-11eb-95dc-97b6527bea7a.png)

**Comment by probonopd** [comment]
For a super quick way to go home:

![image](https://user-images.githubusercontent.com/2480569/105615712-f2071d80-5dd2-11eb-9a07-0d6cd311686e.png)
