### ISSUE TITLE
Live USB not working on Dell E4300

### ISSUE THREAD

**Issue by schusz** [helloSystem/hello#107]
After loading kernel the boot logo shows and then nothing happens. Is there a solution for this?

**Comment by probonopd** [comment]
Hello @schusz
Which version are you using? `hello-0.3.0_0C164-FreeBSD-12.1-amd64.iso
`?

If not, please retry with this version. The FreeBSD logo can take up to three minutes on the Live system. The installed system will be _much_ faster.

**Comment by schusz** [comment]
Hi @probonopd , hello-0.3.0_0C164-FreeBSD-12.1-amd64.iso is the version I am using.

I used 'unset boot_mute' and 'boot -v' to boot in verbose mode.

Booting did not succeed. It kept displaying:

ahcich4: CONNECT requested
ahcich4: AHCI reset...
ahcich4: SATA connect time-out time=10000us status=00000000
ahcich4: reset: device not found

I turned the machine off after 2 hours

**Comment by probonopd** [comment]
Thanks @schusz.
Seemingly some issue wih the SATA controller.
Can you try again with disabling all SATA drives in BIOS?

**Comment by schusz** [comment]
Goodmorning @probonopd , If I disable all SATA it repeatedly shows this:

g_vfs_done():iso9660/LIVE[READ(offset=640415744, length=14336)]error = 5
(dao:umass-sim0:0:0:)0): READ(10). CDB: 28 00 00 10 77 94 00 00
(dao:umass-sim0:0:0:)0): CAM status:CCB request completed with an error
(dao:umass-sim0:0:0:)0): Retrying command, 3 more tries remain

This repeats itself 2 times until 0 more times remain.
Then it says:
(dao:umass-sim0:0:0:)0): Error 5, Retries exhausted

And then it repeats endlessly.

If you want I can send a video of the boot proces.

**Comment by probonopd** [comment]
Could be something that has to do with this USB device.
Can you try another (model of) USB stick?

**Comment by schusz** [comment]
I tried 3 different USB drives.
Booting failed from all 3. Booting from the same sticks works flawlessly on my MacBook Pro8,1.
![Uploading 106179819...]

**Comment by schusz** [comment]
@probonopd Got Wi-Fi working from USB dongle.

**Comment by probonopd** [comment]
> A pity that I can't install it on the Mac's hard drive. 

Why not?

**Comment by grahamperrin** [comment]
https://github.com/helloSystem/hello/issues/107#issuecomment-769272185

> … failed from all 3. …  ![Uploading 106179819...] …

(GitHub didn't get the complete upload.)

### … kernel: … Error 5, Retries exhausted

https://github.com/helloSystem/hello/issues/107#issuecomment-768123645

Do you get this consistently – with _every_ failed boot – for all three USB drives – with the Dell E4300?

If you're willing to share a link to the public result of a hardware probe: 

1. boot from an alternative FreeBSD-based system ([NomadBSD](https://nomadbsd.org/), maybe)
2. have all three drives connected
3. `sudo pkg install sysutils/usbutils sysutils/hw-probe && sudo hw-probe -all -upload`

– then we can think about external hubs (if any), and so on. 

### Defocusing from helloSystem

For comparison: 

[Multiple errors with USB devices : freebsd](https://old.reddit.com/r/freebsd/comments/l4r7ba/multiple_errors_with_usb_devices/) (2021-01-25, not resolved) with reference to: 

* https://pastebin.com/knzQE6Y3 – _FreeBSD-CURRENT /dev/da0 CAM status: CCB request completed with an error_ 

– in very simple terms, one side of this notebook is better than the other. 

Generally, you might find that FreeBSD-based systems are more pernickety about quality of USB hardware (including connectors) than, say, Microsoft Windows. 

### See also

https://github.com/helloSystem/ISO/issues/25#issuecomment-765820298

**Comment by schusz** [comment]
> > A pity that I can't install it on the Mac's hard drive.
> 
> Why not?

Sorry, I forgot to mention the reason. I don't want to remove macOS from it.
I'll try and find out how to install helloSystem on the Dell E4300.
First I'll try @grahamperrin 's suggestion.

**Comment by schusz** [comment]
@grahamperrin Yes, on the De E4300 boot failed consistently on every USB drive.
I'll try to probe the hardware and give you the public link tonight.

**Comment by schusz** [comment]
Hi @grahamperrin I probed my Dell Latitude E4300.||I had one USB hub connected, and had 5USB flash dives inserted in th hub.
This os the public link to the result of the hardware probe:
https://bsd-hardware.info/?probe=84925c014a

**Comment by schusz** [comment]
I found a thread in the FreeBsd forum that discribes a similar issue with a Lenovo Thinkpad E485 and that was solved:

https://forums.freebsd.org/threads/installer-fails-to-boot-hangs-on-at-a-line-ahcich0-ahci-reset.71726/

But I don't know how to try the solution. I hope you can advise.

**Comment by schusz** [comment]
I changed the SATA setting in the BIOS from AHCI to ATA, and then the 'ahcich4: reset: device not found' message did not appear anymore, but now there's the message 'md1.unzip: UZIP(zlib) inflate() failed' message appears 10 times and then the booting freezes.

**Comment by grahamperrin** [comment]
Thanks. 

A minor typo (_uzip_ without the letter _n_): 

> `md1.uzip: UZIP(zlib) inflate() failed`

▶ https://github.com/helloSystem/ISO/issues/102

**Comment by grahamperrin** [comment]
Re: https://github.com/helloSystem/hello/issues/107#issuecomment-771154731

https://bsd-hardware.info/?probe=84925c014a&log=lsusb is interesting 👍 now please let us have a condensed view: 

`lsusb`

**Comment by schusz** [comment]
I'm not sure what you mean by 'let us have condensed view: lsusb'.
What exactly should I do?

**Comment by grahamperrin** [comment]
Sorry! Just run the one-word command at the command line, whilst booted from the NomadBSD drive, with the same (or a similar) set of USB devices connected: 

`lsusb`

**Comment by grahamperrin** [comment]
(There's the wish to perform a safe boot, however https://github.com/helloSystem/ISO/issues/103 this is not yet implemented.)

**Comment by schusz** [comment]
Here'sr the result of the lsusb command:

@NomadBSD ~> lsusb
Bus /dev/usb Device /dev/ugen5.2: ID 046d:c534 Logitech, Inc. Unifying Receiver
Bus /dev/usb Device /dev/ugen0.4: ID 413c:8162 Dell Computer Corp. Integrated Touchpad [Synaptics]
Bus /dev/usb Device /dev/ugen0.3: ID 413c:8161 Dell Computer Corp. Integrated Keyboard
Bus /dev/usb Device /dev/ugen2.2: ID 0a5c:5800 Broadcom Corp. BCM5880 Secure Applications Processor
Bus /dev/usb Device /dev/ugen0.2: ID 0a5c:4500 Broadcom Corp. BCM2046B1 USB 2.0 Hub (part of BCM2046 Bluetooth)
Bus /dev/usb Device /dev/ugen7.2: ID 05e3:0610 Genesys Logic, Inc. Hub
Bus /dev/usb Device /dev/ugen6.1: ID 0000:0000  
Bus /dev/usb Device /dev/ugen5.1: ID 0000:0000  
Bus /dev/usb Device /dev/ugen0.1: ID 0000:0000  
Bus /dev/usb Device /dev/ugen1.1: ID 0000:0000  
Bus /dev/usb Device /dev/ugen2.1: ID 0000:0000  
Bus /dev/usb Device /dev/ugen3.1: ID 0000:0000  
Bus /dev/usb Device /dev/ugen7.1: ID 0000:0000  
Bus /dev/usb Device /dev/ugen4.1: ID 0000:0000

Is that what you need?

**Comment by probonopd** [comment]
Hi ·@schusz, do you have a chance to run this on an entirely different set of hardware - different USB stick, different computer?

**Comment by schusz** [comment]
Hi @probonopd, yes, I have a late 2010 iMac, a 2020 MacBook Pro, the infamous Dell Latitude E4300 (2x), a Dell Latitude E6400, and a Del Latitude E7280. Which helloSystem version do you suggest I use? I have loads of USB 2 and USB 3 flash drives.

**Comment by hcarrega** [comment]
I'm getting some issues to not booting on a acer aspire desktop and on a dell poweredge t110 maybe I burn it wrong

**Comment by probonopd** [comment]
Live boot can take up to 5 minutes and needs at least 4 GB of RAM due to https://github.com/helloSystem/ISO/issues/4.

**Comment by probonopd** [comment]
@schusz if you have some time, why not make 2 bootable sticks (one USB2 and one USB3) and then test on all of them... as long as they have at least 4 GB of RAM. (Maybe except the 2020 MacBook Pro because that is probably too recent.)

**Comment by grahamperrin** [comment]
https://github.com/helloSystem/hello/issues/107#issuecomment-777309112

@hcarrega not necessarily. On each computer: [boot in verbose mode](https://hellosystem.github.io/docs/developer/boot.html#boot-in-verbose-mode).

**Comment by schusz** [comment]
@probonopd I used a different USB-2 and USB-3 drive with r0.3.

I now turned out that where I was not able to boot into helloSystem on the Dell E4300 before, it now worked.
It took a really long time though before it finished.
It even worked on some of the flash drives I tried before.
And r.0.3, r0.4 and r.055 now also worked on the Dell. E4300.
One peculiarity:
The Global Menu did not work as on the other devices. On the E4300 there were 3 right arrows in the menu, and then when you click that, a pull-down menu appears, as can be seen in the photo I took. I'll send it via a Twitter DM.

I did a Hardware Probe for all 4 devices that I booted with these drives.
Used a MacBook Pro 15", Late 2011, an iMac, Late 2010, Dell latitude E4300.

Hardware Probe **Dell Latitude E7280** SanDisk (USB3) en Cruzer (USB 2):
https://bsd-hardware.info/?probe=1e243253d1
Hardware Probe 2 **Dell Latitude E7280** Booted from Cruzer:
https://bsd-hardware.info/?probe=defaee0e5c

Hardware Probe **iMac11,3, late 2010**:
SanDisk  USB3 and SanDisk 2.0https://bsd-hardware.info/?probe=d7cca96f72

Hardwate Probe 1 **MacBook Pro 15" Late 2011**, SanDisk USB3:
https://bsd-hardware.info/?probe=e74d76ecb3
https://bsd-hardware.info/?probe=8f93b4146d

I already gave the HW Probe url for the 4300 earlier.

So this issue seems to be resolved. It actually never existed, if only I waited long enough for the boot to be completed ;-).

**Comment by probonopd** [comment]
Thank you @schusz, really helpful.

> It took a really long time though before it finished.

Can you define "long"? The live system can take up to 5 minutes to boot, typically under 2. The installed system will be much faster.
https://github.com/helloSystem/ISO/issues/4

> The Global Menu did not work as on the other devices. On the E4300 there were 3 right arrows in the menu, and then when you click that, a pull-down menu appears

I suspect this has to do something with the DPI of the screen, and that the fonts are too large as a result and don't fit into the space in the menubar. Please open a separate ticket for this, ideally with details about the screen and/or hardware probe of the device in question.

**Comment by latenightly** [comment]
@schusz how long did it take? I just bought an iMac 2010 today to test out hello. Booted in verbose mode. There were a few Warnings, but it keeps going until it gets to play the intro music. The music finishes but even 10-15 minutes later, still only a black screen.

**Comment by schusz** [comment]
Hi @latenightly I just booted my late 2010 iMac 27" from a USB2 flash drive and it took 3 minutes for the desktop to appear. helloSystem build 0E223 for commit b6811af.

**Comment by latenightly** [comment]
Hi @schusz, thanks for the response. I used the the same build and it did not work. I am using an iMac 21" of mid 2010. I wonder what the issue might be. I tried to find if it is an issue with the GPU unit but I did not get quite far.

I just tried again: when the music starts playing, I only see a black screen. Still after minutes nothing happens.
Any idea on how to tackle this another way?

**Comment by schusz** [comment]
Hi @latenightly I had this a long time ago and can't remember what te steps are from the top of my head, but I've had the samenissue back then. You may find a solution in this topic: https://github.com/helloSystem/ISO/issues/203

**Comment by probonopd** [comment]
> @schusz how long did it take? I just bought an iMac 2010 today to test out hello. Booted in verbose mode. There were a few Warnings, but it keeps going until it gets to play the intro music. The music finishes but even 10-15 minutes later, still only a black screen.

Does your iMac have a Radeon GPU? Then you might possibly be running into https://github.com/helloSystem/ISO/issues/147.

**Comment by grahamperrin** [comment]
Cross-reference: 

[Freeze boot FreeBSD 13.0 | The FreeBSD Forums](https://forums.freebsd.org/threads/freeze-boot-freebsd-13-0.81797/) – [yesterday's update](https://forums.FreeBSD.org/threads/freeze-boot-freebsd-13-0.81797/post-529937) from the opening poster.
