### ISSUE TITLE
Consider endorsing the Zig programming language

### ISSUE THREAD

**Issue by darltrash** [helloSystem/hello#109]
I just found this project and I was thinking it would be nice to endorse the [Zig programming language](https://ziglang.org/) as a first-class citizen (Like Python).

It's a language designed to be secure and fast by default, do interop with C and act as a [Powerful Drop-In Replacement for GCC/Clang](https://andrewkelley.me/post/zig-cc-powerful-drop-in-replacement-gcc-clang.html).

It should work just fine under FreeBSD.

Sadly, it is still a beta and it's not production ready, but i thought that it still is a nice idea to consider it in future

**Comment by probonopd** [comment]
Hello @darltrash.

please check out our developer information at https://hellosystem.github.io/docs/developer/architecture.
At this point, we encourage developers to use PyQt, Qml, and Qt, although we are not particularly fond of C++. Does Zig interface with Qt?

**Comment by darltrash** [comment]
- **Does Zig interface with Qt?**
    _It should, considering that Zig is compatible with most C libraries, so a C QT binding should do the job_

- **Does Zig do away with pointers?**
    _I am not sure what this question means, but zig does have pointers and slices._

- **Does Zig do away with the need for manual memory management?**
    _I dont get this question neither, but yes, it does need manual memory management for things that dont have a known size at compiletime, but it's really easy to do arraylists, hashmaps and etcetera_

**Comment by probonopd** [comment]
I was referring to the fact that in Python there are no pointers an application developer has to mess with, and memory is managed automatically so the application developer does not have to manually allocate nor free it.

**Comment by darltrash** [comment]
> I was referring to the fact that in Python there are no pointers an application developer has to mess with, and memory is managed automatically so the application developer does not have to manually allocate nor free it.

Aw shucks, It seems like Zig doesnt fits your description, I am sorry for wasting your time.
But, Why no manual allocations or pointers? I dont really think heavily relying in highly abstracted OOP scripting languages is exactly a good idea for all usecases, specially if you need to write a high-performance program that requires lower levels of abstraction to work.

Anyways, I am nobody to judge and maybe this is a great idea considering that deploying apps with QT and Python is extremely easy and can boost development for helloSystem by a lot.

Thanks for reading, Have an amazing day!

**Comment by probonopd** [comment]
Thanks for bringing Zig to my attention @darltrash - I am sure it is good in what it does, but at this time we are not looking for a "better C/C++" for helloSystem.
