### ISSUE TITLE
No start in macbook 2009

### ISSUE THREAD

**Issue by SergioBG** [helloSystem/hello#114]
Hi, try testing the system on a macbook 2009.
The laptop detects the usb and starts the efi system, but when the splas screen appears, it is completely frozen, it is not possible to access the terminal. 
Nothing to do , only black screen.
Sorry for my english , cheers

**Comment by SergioBG** [comment]
Ok , the system finally start but is very slow for show the desktop. After this is very usable.Nice work

**Comment by probonopd** [comment]
It will be much faster booting after installation to hard disk.

Live ISO boot is slow because of https://github.com/helloSystem/ISO/issues/4-
