### ISSUE TITLE
The system keep locked to this point 

### ISSUE THREAD

**Issue by 15locraft** [helloSystem/hello#115]
![Screenshot_freebsd12 0_2021-02-11_16:28:41](https://user-images.githubusercontent.com/76566839/107658392-61f81d80-6c86-11eb-939d-7ebfd4016e31.png) on qemu last version using virt manager

**Comment by probonopd** [comment]
Do you have at least 4 GB RAM assigned?

**Comment by 15locraft** [comment]
No

**Comment by probonopd** [comment]
That is the reason then. As per the documentation, helloSystem currrently needs at least 4 GB of RAM until someone solves https://github.com/helloSystem/ISO/issues/4.
