### ISSUE TITLE
Cleaning up the docs?

### ISSUE THREAD

**Issue by 69graves** [helloSystem/hello#118]
Hey there,

I am not a programmer, but I can help.  

Could I be tasked with correcting typographical errors in the main docs?

It would be a trivia thing for me to do, and I would be absolutely thrilled to contribute in this way.

**Comment by probonopd** [comment]
Hello @69graves

Yes, this would be very welcome.

Simply go to a page on https://hellosystem.github.io/docs/, then click on "Edit on GitHub" in the upper right corner.

Then click on ![image](https://user-images.githubusercontent.com/2480569/107885911-2915ae00-6efd-11eb-9b11-f0c5dafcca2d.png) to edit the file.
