### ISSUE TITLE
Uniform styles

### ISSUE THREAD

**Issue by wesbluemarine** [helloSystem/hello#133]
![desktop](https://user-images.githubusercontent.com/14043560/108630204-efe0bf00-7463-11eb-88c6-d69fc9065502.png)

I think "Cancel" and "Ok" buttons should be like "Close".
Since everything is "roundish", I think the dock background might have rounded top corners like in MacOS Yosemite.

**Comment by probonopd** [comment]
The about box could do without any button at all since it is not a dialog.

**Comment by linuxkettle** [comment]
> we are aiming for a 10.4 feel

Ah, my favourite OS X release. It's a shame it's unsupported now.

**Comment by probonopd** [comment]
With https://github.com/helloSystem/QtPlugin/issues/2 being no more the case at least with Filer,

> I think "Cancel" and "Ok" buttons should be like "Close"

is fixed in the upcoming release. Hence cosing.
