### ISSUE TITLE
Cannot boot in VirtualBox nor bare metal

### ISSUE THREAD

**Issue by gianmarcogg03** [helloSystem/hello#136]
Everytime I try to boot on VirtualBox or on a real machine I get a rescue prompt and I can't exit out of it or boot into a GUI.
Excuse the poor quality photo: https://imgur.com/a/BlXfvZl

**Comment by probonopd** [comment]
Did you assign at least 4 GB RAM?
https://hellosystem.github.io/docs/user/getting-started

**Comment by gianmarcogg03** [comment]
Now I get this. Although I still can't run it on bare metal because the PC I used has 3GB of RAM so whatever.
![image](https://user-images.githubusercontent.com/28053717/108846278-aff21700-75de-11eb-9145-b4a7a7ffc6d9.png)

**Comment by probonopd** [comment]
You need at least 4 GB of RAM assigned to the machine.

**Comment by gianmarcogg03** [comment]
I gave it 6GB now, and it still doesn't work.

**Comment by probonopd** [comment]
Which exact ISO did you download?

**Comment by gianmarcogg03** [comment]
https://github.com/helloSystem/ISO/releases/tag/r0.4.0

**Comment by probonopd** [comment]
Strange. That version is generally known to boot well. 
Please describe your hardware, host operating system, and virtual machine setup.

**Comment by gianmarcogg03** [comment]
CPU: Intel Pentium G4400 (dual core) with integrated graphics
RAM: 16 GB
OS: Arch Linux
VM: VirtualBox 6.1.18 r142142, 2 cores, 6043 MB of RAM, VBoxSVGA with 128 MB of video memory

**Comment by probonopd** [comment]
> CPU doesn't support long mode

You are running on a 64-bit host OS, and have configured the VM to be 64-bit?

**Comment by gianmarcogg03** [comment]
Yes, I did.

**Comment by acook** [comment]
I'm able to boot 0.5.0 in VirtualBox with 4GB of RAM. Did you see if FreeBSD would boot?

**Comment by gianmarcogg03** [comment]
I tried a stock FreeBSD amd64 ISO but I get the same issue.

**Comment by probonopd** [comment]
@gianmarcogg03 you do have more than 4 GB in your host PC now?

**Comment by probonopd** [comment]
What happens if you type `boot` and press Enter?

**Comment by gianmarcogg03** [comment]
`CPU doesn't support long mode`

**Comment by probonopd** [comment]
Is virtualization enabled in your host machine's BIOS?

**Comment by gianmarcogg03** [comment]
I have that enabled in the BIOS already, also when I look up the error online I only get people that tell to enable that BIOS option. This is very weird.

**Comment by grahamperrin** [comment]
https://github.com/helloSystem/hello/issues/136#issuecomment-785376817

> … VBoxSVGA …

Please, what's your reason for preferring a non-recommended controller? 

![image](https://user-images.githubusercontent.com/192271/110215820-b4061a80-7ea3-11eb-9812-b516adc9f65e.png)

If you allow the recommended controller, then does there remain a yellow alert for any other aspect?

**Comment by gianmarcogg03** [comment]
I selected another one that makes the warning disappear and it still doesn't work.

**Comment by grahamperrin** [comment]
From your opening post: 

> ![image](https://user-images.githubusercontent.com/192271/111593543-f68ff700-87c1-11eb-934a-7af99b037d9c.png)

Is that still the problem?

**Comment by gianmarcogg03** [comment]
That's only on that laptop, on VirtualBox I get "CPU doesn't support long mode".

**Comment by grahamperrin** [comment]
Thanks. Please let us have the most recent log. 

![image](https://user-images.githubusercontent.com/192271/111831247-fb9a9680-88e6-11eb-8ca2-59ba1197fd42.png)

**Comment by gianmarcogg03** [comment]
[helloSystem-2021-03-18-10-59-41.log](https://github.com/helloSystem/hello/files/6174461/helloSystem-2021-03-18-10-59-41.log)

**Comment by grahamperrin** [comment]
Please try this: 

[helloSystem issue 136.ova.zip](https://github.com/helloSystem/hello/files/6174695/helloSystem.issue.136.ova.zip)

**Comment by gianmarcogg03** [comment]
![image](https://user-images.githubusercontent.com/28053717/111866335-0ac42780-896d-11eb-83ca-5e63c7901728.png)

**Comment by grahamperrin** [comment]
I left the optical drive empty, ready for you to attach your copy of the `.iso`: 

![image](https://user-images.githubusercontent.com/192271/111875978-6fdf4380-8994-11eb-8957-0a6f26cf5b7f.png)

Sorry for not making this clear.

**Comment by gianmarcogg03** [comment]
After saying "Press ENTER to boot immediately" or whatever now I get this blank screen with a cursor.
![image](https://user-images.githubusercontent.com/28053717/111880335-2a7a4080-89ab-11eb-8a79-447359fdf561.png)

**Comment by probonopd** [comment]
Please boot in [verbose mode](https://hellosystem.github.io/docs/developer/boot.html#boot-in-verbose-mode).

**Comment by gianmarcogg03** [comment]
I left it doing its thing and now it works, so I guess I just had to wait for that blank screen to go away by itself.
![image](https://user-images.githubusercontent.com/28053717/111880540-6eba1080-89ac-11eb-83e2-db56257bce8d.png)

**Comment by grahamperrin** [comment]
@gianmarcogg03 please review the _General_ preferences for the virtual machine(s) that did not work for you: 

* https://github.com/helloSystem/hello/issues/136#issuecomment-787195472 for a helloSystem ISO
* https://github.com/helloSystem/hello/issues/136#issuecomment-787487344 for a FreeBSD ISO. 

If **not** already set to _BSD_ and _FreeBSD (64-bit)_: 

![image](https://user-images.githubusercontent.com/192271/111882911-26045680-89b0-11eb-8f01-147b05c9c98b.png)

* please set the preferences. 

If both _BSD_ and _FreeBSD (64-bit)_ were already set: 

* you can compare the workable settings from the `.ova` file that I provided, with the settings in your non-working machine(s). 

Thanks.
