### ISSUE TITLE
Merge titlebar with menubar

### ISSUE THREAD

**Issue by Lestibournes** [helloSystem/hello#141]
One of the things that keeps me using Unity on Ubuntu is this neat space-saving feature that makes maximized windows feel almost like full screen windows. That and global menu are the main reasons why I don't feel like I can switch to something else. It makes the system feel so clean and spacious.

**Comment by probonopd** [comment]
hello @Lestibournes

As helloSystem wants to be welcoming to switchers from the Mac, we want to show a consistent window **title bar** all the time, except when the application is in full screen. Otherwise the user would not see the title of the window, which would be very annoying.

> Note that the most difficult kind of consistency to achieve is matching people’s expectations. Because you often face a wide audience and a range of expertise, it’s difficult to meet the expectations of everyone. You can address this problem by carefully weighing the consistency issues in the context of your target audience and their needs.

Source: [Macintosh Human Interface Guidelines](https://dl.acm.org/doi/book/10.5555/573097)

**Comment by Lestibournes** [comment]
I understand that consistency and simplicity are very important, however from reading what you wrote it seems that you are not trying to copy Mac OS X but rather to follow the same design principles in order to create something familiar. That sounds like it leaves room to improve over what Mac OS X did, and in my opinion when it comes to the titlebar/menubar Unity does provide an improvement. On the consistency issue, when a window is maximized the top bar, which includes the menubar, becomes the titlebar both visually and functionally so the title of the window is being consistently displayed in the same place. At least, that is my experience as someone who's used Ubuntu since 6.06 and I only spent 1 week with a Macbook Air in 2014. Back then I thought that on this point Unity was superior despite being so similar.

**Comment by probonopd** [comment]
Yes @Lestibournes we do take the liberty to (what we think) improve over the 80s-00s design principles. However, this feature request is not in line with our design philosophy which mandates for the title bar to always be the same no matter what. (The only exception being full-screen.)

**Comment by grahamperrin** [comment]
> Merge titlebar with menubar

https://github.com/helloSystem/hello/issues/148#issuecomment-793123656
