### ISSUE TITLE
Build attempt returns:: realpath: missing operand

### ISSUE THREAD

**Issue by DroWnThePoor** [helloSystem/hello#144]
I'm experiencing this issue when attempting to build on Ubuntu 18.04:

$ sudo ./build.sh hello.iso
releases
realpath: missing operand
Try 'realpath --help' for more information.
/settings/packages.hello.iso is missing, exiting

Additionally if I don't specify the hello.iso filename as in the docs example, the last line instead prints as this:

/settings/packages.xfce is missing, exiting

From what I can tell realpath is a somewhat out of use command for expanding symbolic links? It appears to be present on my system, but I have no idea where to go from here.

**Comment by probonopd** [comment]
hello @DroWnThePoor

What host system are you trying to run `build.sh` on?

**Comment by DroWnThePoor** [comment]
I mentioned in the issue I'm on Ubuntu 18.04. It's a 64-bit Intel box.

**Comment by probonopd** [comment]
You can only run `build.sh` on FreeBSD (same major version as the one you are trying to build).

You could, for example, install https://github.com/helloSystem/ISO/releases/tag/r0.4.0 and use that to run `build.sh`.
