### ISSUE TITLE
Screen resolution not right. the dock display not full

### ISSUE THREAD

**Issue by cnmade** [helloSystem/hello#149]
![image](https://user-images.githubusercontent.com/278153/109752745-ef8eb380-7c1b-11eb-84fd-1a8c1931c2fa.png)

Screen resolution not right. the dock display not full, I just boot into fresh iso. nothing changed.

**Comment by probonopd** [comment]
Are you running this in VMware? Then this might be an effect of
https://github.com/helloSystem/hello/issues/101

**Comment by netroby** [comment]
yes, i using vmware.

**Comment by probonopd** [comment]
Thanks @netroby. Closing here, let's continue in #101.
