### ISSUE TITLE
Port TextEdit?

### ISSUE THREAD

**Issue by 69graves** [helloSystem/hello#150]
As I use my Mac more, and TextEdit,  come to realize that it's a pretty powerful text editor, at least for writing, which is my field of expertise, but perhaps not for coding.  

It's been a while since I've used the GNUStep version, but maybe this is something to consider?

**Comment by probonopd** [comment]
hello @69graves, TextEdit should run on helloSystem, albeit without integration into the native helloSystem menu.

**Comment by 69graves** [comment]
Then I will look into getting it running.  I didn't see it in /usr/ports.   I will continue looking and try it out.

**Comment by probonopd** [comment]
Right, I think it is no longer in Ports/Packages but it can probably be compiled from e.g., https://github.com/ericwa/TextEdit
