### ISSUE TITLE
Basis, components and direction of helloSystem

### ISSUE THREAD

**Issue by grahamperrin** [helloSystem/hello#159]
https://github.com/helloSystem/hello/wiki/Welcome-and-unwelcome-technologies first and second paragraphs: 

> … We are building minimalistic end-user appliances (embedded systems for the desktop, possibly for media consumption devices and other form factors) that happen to use a Linux kernel as its hardware abstraction layer, but otherwise has not much in common with a "Linux distribution".
> 
> In fact, we may even want to use another kernel such as FreeBSD. …

helloSystem does not use a Linux Kernel … and so on. 

Other parts of the _Welcome and unwelcome technologies_ page may be outdated or incomplete. 

https://github.com/helloSystem/hello/wiki/Components#core-os

> * … FreeBSD was chosen

https://github.com/helloSystem/hello/issues/52 can be closed. 

Also, maybe close https://github.com/helloSystem/hello/issues/37 – _thoughts on_ the underlying system are not expected to change the choice of FreeBSD as the basis. 

> * … The helloSystem Live ISO build system is based on FuryBSD, and helloSystem is using some code (initgfx) from NomadBSD. …

https://github.com/helloSystem/hello/issues/16

It will be nice to have a roadmap, to include: 

* a future shift in emphasis from _live_ boot, to _installations_ of helloSystem. 

Thanks

**Comment by grahamperrin** [comment]
Parts of the _Components_ page may be outdated. 

For example, https://github.com/helloSystem/hello/wiki/Components#utilities lists `lumina-screenshot` however: 

* https://github.com/helloSystem/ISO/blob/73c787a4e0c5f658aadc8d25147b513068b1607b/overlays/uzip/hello/files/usr/share/skel/dot.config/lxqt/globalkeyshortcuts.conf#L33 specified `lximage-qt` 
* FreeBSD bug [254420 – graphics/lximage-qt should no longer be described as a screenshot tool](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=254420)
* [x11/screengrab](https://www.freshports.org/x11/screengrab/) is preferred.

**Comment by probonopd** [comment]
```
No packages available to install matching 'screengrab' have been found in the repositories
```

**Comment by grahamperrin** [comment]
OK, `lximage-qt` for as long as users will be prevented from using superior applications.

**Comment by probonopd** [comment]
Note: That page reflects brainstorming of potential components for helloSystem. The components that have been decided on are marked with  :arrow_right:.

**Comment by dbisping** [comment]
Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. 

O the joy of my spirit - it is uncaged - it darts like lightning!
It is not enough to have this globe or a certain time,
I will have thousands of globes and all time.

- Walt Whitman
