### ISSUE TITLE
Split screen 

### ISSUE THREAD

**Issue by schusz** [helloSystem/hello#163]
@probonopd 
In both Live and installed versions of hello-0.5.0_0E142-FreeBSD-13.0-amd64.iso and hello-0.5.0_0E157-FreeBSD-13.0-amd64.iso (on Dell Latitude E4300; hardware Probe https://bsd-hardware.info/?probe=d5051ef185#Devices) the Global Menu's top half is not visible.

And the screen is split in two.
The right part of the desktop occupies approx. left 4/5th of the screen, and the left part occupies right 1/5th of the screen. It is not possible to cross the dividing border with the mouse pointer.

![photo_2021-04-07_20-47-29](https://user-images.githubusercontent.com/32078425/113926653-ba621c00-97ec-11eb-97ee-9f2f65cf8fdb.jpg)

**Comment by LouiIPSW** [comment]
set the set resolution to native

**Comment by schusz** [comment]
Setting the resolution to native doesn't work.

**Comment by schusz** [comment]
E183-13.0 Live and Installed boot into GUI, but still have the spit screen.

**Comment by probonopd** [comment]
Just to be sure, with 12.2 based builds you don't have this issue, correct?

**Comment by schusz** [comment]
@LouiIPSW How can I set the resolution to Native?
I tried it with the Screen Layout Editor.

**Comment by probonopd** [comment]
Can you please post the outputs of `xrandr` (without any arguments) when the screens looks as it should and when there is a problem?

**Comment by schusz** [comment]
@probonopd That's right, with the 12.2 base builds I do not have the split screen and the Global Menu is fully visible.

**Comment by schusz** [comment]
@probonopd 
**Output of `xrandr`**
On E184-12.2:
```
Roels-Latitude-E4300% xrandr
Screen 0: minimum 320 x 200, current 1280 x 800, maximum 8192 x 8192
LVDS-1 connected primary 1280x800+0+0 (normal left inverted right x axis y axis) 286mm x 179mm
1280x800 59.97*+ 59.81 59.91 40.00
1280x720 59.86 59.74
1024x768 60.00
1024x576 59.90 59.82
960x540 59.63 59.82
800x600 60.32 56.25
864x486 59.92 59.57
640x480 59.94
720x405 59.51 58.99
640x360 59.84 59.32
VGA-1 disconnected (normal left inverted right x axis y axis)
HDMI-1 disconnected (normal left inverted right x axis y axis)
DP-1 disconnected (normal left inverted right x axis y axis)
HDMI-2 disconnected (normal left inverted right x axis y axis)
DP-2 disconnected (normal left inverted right x axis y axis)
DP-3 disconnected (normal left inverted right x axis y axis) 
```

On E183-13.0:
```
Roels-Latitude-E4300% xrandr
xrandr: Failed to get size of gamma for output default
Screen 0: minimum 1280 x 800, current 1280 x 800, maximum 1280 x 800
default connected 1280x800+0+0 0mm x 0mm
1280x800 0.00* 
```

**Comment by schusz** [comment]
@probonopd 0E185-13.0: still split screen.
Output of xrandr same as 0E183-13.0

**Comment by probonopd** [comment]
Yes, that's expected - nothing has changed in that area. But thanks for confirming.

**Comment by schusz** [comment]
@probonopd I managed to get rid of the split screen. I googled a lot and almost gave up. But to be honest I am not sure anymore what exactly did the trick. It's late now, so I can not try and repeat what I did.
Possibly installing this package solved the issue:
`sudo pkg install -y xf86-video-intel`
I will reinstall helloSystem 0E185 again and repeat what I did, and pay attention carefully.
I'll let you know when I found the solution.

**Comment by probonopd** [comment]
Indeed we have some packages missing from our package list for FreeBSD 13 for reasons I don't fully understand; so I am going to try adding them back.... 
* For 12: https://github.com/helloSystem/ISO/blob/experimental/settings/packages.common-12
* For 13: https://github.com/helloSystem/ISO/blob/experimental/settings/packages.common-13

**Comment by schusz** [comment]
Hey @probonopd Just confirming that 

sudo pkg install -y xf86-video-intel

solved the 'split screen'issue.

I will install 0E190 tonight and report back.

**Comment by schusz** [comment]
Hey @probonopd , 13.0 0E190 on my Dell Latitude E4300 has no split screen anymore. Thanks :-).

**Comment by probonopd** [comment]
Thanks for re-testing and confirming @schusz.
