### ISSUE TITLE
offer darkmode from install

### ISSUE THREAD

**Issue by devrob20** [helloSystem/hello#171]
please dont make the misstake linux users do, and build in a darkmode option from install to boot and using the OS. This is a critical feature of ppl with low vision.  

i like the theming, but mcmojave dark and circles profile a more modern look and feel, pls include in the next versions

**Comment by alphamodh0** [comment]
Yes, a lot of users loves dark mode. We need a confortable OS.

**Comment by probonopd** [comment]
helloSystem does not have a dark mode as it violates https://dl.acm.org/doi/book/10.5555/573097.

**Comment by kettle-7** [comment]
If you were to add an option somewhere to enable dark theming, I think you'll find a lot of people use it. I understand not using it by default.

**Comment by probonopd** [comment]
Maybe.

To me, it is very un-Mac-like.
It negates the modern GUI that was invented at XEROX PARC.

It's like falling back to the (literally) dark times before the Lisa and the Mac when screens looked like this:

![image](https://user-images.githubusercontent.com/2480569/135770898-63507d85-0bf5-4b9f-b474-2746a705070d.png)

**Comment by kettle-7** [comment]
heh, top hasn't changed much ;~)

**Comment by louies0623** [comment]
I have seen several doctors also use dark mode, because they have to stare at the screen for a long time to record cases.
