### ISSUE TITLE
Google sometimes denies login when Falkon is used

### ISSUE THREAD

**Issue by bmentink** [helloSystem/hello#178]
gmail webapp does not like Falkon, I even changed the "User Agent" to mozilla/chrome but still no joy ...
![gmail](https://user-images.githubusercontent.com/10123911/123185152-3fabb300-d463-11eb-8d78-cfc3c126bfc3.jpg)

**Comment by linuxkettle** [comment]
I have the same problem. For a workaround, install Mozilla Thunderbird (`sudo pkg install thunderbird`), and put this in ~/Applications: [Thunderbird.app](https://github.com/helloSystem/hello/files/6706874/thunderbird.app.tar.gz). It's just a wrapper app bundle, I couldn't be bothered putting up with gradle for this.

**Comment by linuxkettle** [comment]
You can also get Firefox (`sudo pkg install firefox`) and I've got a wrapper bundle here:
[Firefox.app](https://github.com/helloSystem/hello/files/6706994/Firefox.app.tar.gz)

**Comment by linuxkettle** [comment]
I believe the problem is related to the version itself; Google will only support the latest ESR version of Firefox and up, if Falkon bears a lower version in its user agent string then Google will assume it's outdated and doesn't have the latest security fixes.

**Comment by probonopd** [comment]
This is a very annoying problem with Google indeed. Strangely, this happens only _sometimes_ and I was not able to find out a clear pattern yet. I can log into _most_ of my Google accounts _most_ of the time, but it seems kinda random. Any insights appreciated!

As a last resort, there is also `sudo pkg install chromium`.

**Comment by bmentink** [comment]
@probonopd   Thanks, yes I indeed did install Chromium out of frustration. I guess there will be a chromium.app at some point?
By the way, really impressed with hello so far , good job all ..

**Comment by linuxkettle** [comment]
>  this happens only sometimes

I've never had it not happen.

> I guess there will be a chromium.app at some point?

I think @probonopd has made one, seeing screenshots of earlier helloSystem versions.

**Comment by probonopd** [comment]
`sudo pkg install chrome` should do the trick.

Did you try to 
* Set the user-agent of Falkon to `Mozilla/5.0 (X11; FreeBSD x86_64; rv:72.0) Gecko/20100101 Firefox/72.0`
* Enable access for "less secure" applications on your Gmail account
* ?

**Comment by bmentink** [comment]
@probonopd 
Yes, I did try to set the user agent as my my original post on this issue. I do have "less secure" already enabled on my gmail account ..
For now I am using Firefox, and that is perfectly fine for my needs. (I am hoping one day that the Brave browser will be ported to FreeBSD, even more secure than Falkon ...

**Comment by probonopd** [comment]
Please try this exact one: `Mozilla/5.0 (FreeBSD; like Intel Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1.2 Safari/605.1.15`

**Comment by bmentink** [comment]
Yep, that works .. cheers!
