### ISSUE TITLE
Folder confusion ..

### ISSUE THREAD

**Issue by bmentink** [helloSystem/hello#180]
I am a bit confused over the operation of some folders.

For example: 

1. If I double click on "Applications" or "System" in a  root window (Opening "Startvolume"), they do nothing.
2. If I double click some User folders like "Documents" it opens up an empty window .. seems empty folder are inconsistent.
3. If I double click Users, and my user "bmentink" window is already open, the double clicking "Users" does nothing, not even highlight the already open user window. If my user window is NOT open, then double clicking "Users" does the correct thing of opening up a folder with Users in it .. bmentink in my case.
4. Clicking in the Menu Go->Applications does nothing. Is there several "Application" locations?

Cheers,

**Comment by probonopd** [comment]
Are you talking about Spatial mode?
Which exact version of helloSystem are you running?

Please try to reproduce like this:

* Check Edit -> Preferences -> Make sure "Spatial mode" is enabled
* Press Command+Ctrl+esc, click on the Desktop to kill all running Filer instances (just to make sure that no windows or tabs are open anymore somewhere)
* Press Command+Ctrl+T to open the Terminal
* Run `launch Filer --desktop`
* Double click Startvolume on the Desktop
* Double click on "Applications", it should open a new Applications window
* Double click on "Startvolume", it should open a new Applications window
* Double click on some User folders like "Documents", it should open a window (empty of the folder is empty)
* If your "bmentink" window is already open, the double clicking "Users" should open or bring to the front the "Users" window

**Comment by bmentink** [comment]
> Are you talking about Spatial mode?
> Which exact version of helloSystem are you running?

The 0.5.0 Release, i.e: `FreeBSD 12.2-RELEASE r366954 GENERIC`
> 
> Please try to reproduce like this:
> 
>     * Check Edit -> Preferences -> Make sure "Spatial mode" is enabled

It is.

> 
>     * Press Command+Ctrl+esc, click on the Desktop to kill all running Filer instances (just to make sure that no windows or tabs are open anymore somewhere)

Which is the "Command key"? I am using the strawberry pi keyboard and mouse, if the command key is the strawberry key, then 
the above command does nothing. I closed all folder window manually. EDIT: Ah, I had to use Ctrl/Alt/Esc that produced a kill mouse icon and all filer winders closed and the background went black.

> 
>     * Press Command+Ctrl+T to open the Terminal

ok

> 
>     * Run `launch Filer --desktop`

I get the following in the Terminal window:

```
Dell-T3500% launch Filer --desktop
# Descending into "/Applications/Video"
# Descending into "/Applications/Graphics"
# Descending into "/Applications/Utilities"
# Descending into "/Applications/Developer Preview"
# Descending into "/Applications/3D Printing"
# Descending into "/Applications/Developer"
# Descending into "/Applications/Audio"
# Descending into "/Applications/Preferences"
# Descending into "/Applications/Office"
# Descending into "/Applications/Autostart"
################### Checking "/System/Filer.AppDir/AppRun"
# Found "/System/Filer.AppDir/AppRun"
Took 8 milliseconds to find candidates via the filesystem
Candidates: (QFileInfo(/System/Filer.AppDir/AppRun))
Selected candidate: "/System/Filer.AppDir/AppRun"
```


> 
>     * Double click Startvolume on the Desktop

Get window with Applications + System + Users

> 
>     * Double click on "Applications", it should open a new Applications window

No, nothing happens.

> 
>     * Double click on "Startvolume", it should open a new Applications window

No, nothing happens

> 
>     * Double click on some User folders like "Documents", it should open a window (empty of the folder is empty)

Only If I Click Users->bmentink

> 
>     * If your "bmentink" window is already open, the double clicking "Users" should open or bring to the front the "Users" window

Yes, it highlights the title bar.

**Comment by probonopd** [comment]
> Which is the "Command key"?

The key left to the Space bar. Has "Alt" printed on it on PC/Raspberry Pi keyboards, and an Apple logo on Mac keyboards.

**Comment by bmentink** [comment]
> > Which is the "Command key"?
> 
> The key left to the Space bar. Has "Alt" printed on it on PC/Raspberry Pi keyboards, and an Apple logo on Mac keyboards.

Yes, I found it, See my EDIT in the comment above .. ;)

**Comment by probonopd** [comment]
What happens if you double-click on the text below the icon rather than the icon itself?

**Comment by bmentink** [comment]
Sorry, which icon are we talking about?

**Comment by bmentink** [comment]
Ahh I see what you mean .. I can double-click on the text for Applications and it opens the window correctly .... it's that issue with clickable area again .. bah!
