### ISSUE TITLE
Cannot use Caps Lock

### ISSUE THREAD

**Issue by louies0623** [helloSystem/hello#181]
When I use the Caps Lock key while typing, it doesn’t work and it doesn’t light up. It only works when I switch it during startup. After I enter the system, it automatically switches to off. 
Cannot be used on laptops, USB keyboards or other PCs.

**Comment by probonopd** [comment]
It is disabled by default. 

You can change it at
Applications -> Preferences -> Keyboard -> Disable the Caps Lock key.

**Comment by louies0623** [comment]
When some designers are making posters, especially movie posters, there is a long string of text to be entered and must be capitalized. Your hand is especially important for those who have only one hand to type because of injury. Keep pressing the Shift key to type a long list of articles, which is extremely inconvenient for the user's hands.

**Comment by probonopd** [comment]
@louies0623 answered over at https://github.com/helloSystem/hello/issues/182:

> When some designers are making posters, especially movie posters, there is a long string of text to be entered and must be capitalized. Your hand is especially important for those who have only one hand to type because of injury. Keep pressing the Shift key to type a long list of articles, which is extremely inconvenient for the user's hands.
