### ISSUE TITLE
It is disabled by default. This is by design since many people find this key annoying. What is your use case for it?

### ISSUE THREAD

**Issue by louies0623** [helloSystem/hello#182]
When some designers are making posters, especially movie posters, there is a long string of text to be entered and must be capitalized. Your hand is especially important for those who have only one hand to type because of injury. Keep pressing the Shift key to type a long list of articles, which is extremely inconvenient for the user's hands.

**Comment by probonopd** [comment]
I think this is the answer to https://github.com/helloSystem/hello/issues/181, so closing here.

**Comment by linuxkettle** [comment]
Try poking around with start-hello. There used to be an option in 'Shortcut Keys' for enabling Caps Lock and swapping Ctrl and Alt.

I use caps lock as a compose key.

**Comment by probonopd** [comment]
> I use caps lock as a compose key.

How?
