### ISSUE TITLE
Caps lock should not be disabled by default

### ISSUE THREAD

**Issue by louies0623** [helloSystem/hello#184]
There is another thing that some Mac or PC users will not know that you turn this setting off. It is true that very few people usually use it, but if you suddenly want to use it but find that it can’t be used, it will take more time to find the keyboard setting. How do they feel like "This is not less or more, which is even more inconvenient" because they can be capitalized by pressing a keyboard button, not to spend time looking for that complicated setting..

**Comment by probonopd** [comment]
This is by [design](https://github.com/helloSystem/hello/wiki/Welcome-and-unwelcome-technologies).

As Steve Jobs said, you can please _some_ people _some_ of the time. But not all people all of the time.

**Comment by linuxkettle** [comment]
Maybe you can please more people trying to type ãççęñțş on a US keyboard with a compose key.

**Comment by probonopd** [comment]
Wow, never knew that a [Compose key](https://en.wikipedia.org/wiki/Compose_key) exists.
We should definitely [consider](https://github.com/helloSystem/hello/issues/186) it.

**Comment by louies0623** [comment]
By the way, the keyboard utility program cannot be opened 
`env: python3.7 No such file or directory.`

**Comment by probonopd** [comment]
This would have been worth its own bug ticket, but I hope I fixed it in 37326c8.

**Comment by linuxkettle** [comment]
Don't hardcode python 3.7!

**Comment by probonopd** [comment]
That's exactly what https://github.com/helloSystem/Utilities/commit/37326c88889d3d90a654ab0c765e5fbba519c257 is doing ;-)

**Comment by louies0623** [comment]
303/418 guide PDF The description clearly expresses that the button is not locked by default.
> The Caps Lock key latches in the down position when pressed and releases
 when pressed again. (On PowerBook computers this key is a soft switch, so it
 doesn't latch.) Note that the Caps Lock key operates for Roman languages
 only; in other words, it works as described in this section for languages that
 include uppercase and lowercase letters. When down, it gives the uppercase
 letter on alphabetic keys. Caps Lock has the same effect on alphabetic keys
 that the Shift key has, but Caps Lock has no effect on any other keys. In other
 words, even when Caps Lock is down, the user must press the Shift key to
 produce the upper characters (#, ?, and so on) on the nonalphabetic keys.
