### ISSUE TITLE
2012 .. 2014 Mac Mini i5 For my hello test machine, any issues?

### ISSUE THREAD

**Issue by bmentink** [helloSystem/hello#187]
Hoping someone has one of these, thinking of buying a cheap one for testing.

I will be using this guide to "bless" the installation: [https://forums.freebsd.org/threads/freebsd-bless-efi-partition-on-mac-hardware.67201/](url)

Thanks

**Comment by probonopd** [comment]
Let's see what http://bsd-hardware.info/?d=helloSystem says:

- Late 2012 = [Macmini6,1](http://bsd-hardware.info/?view=computers&type=mini+pc&vendor=Apple&model=Macmini6%2C2) (there are two helloSystem probes) and Macmini6,2
- Late 2014 = [Macmini7,1](http://bsd-hardware.info/?view=computers&type=Mini+pc&vendor=Apple&model=Macmini7%2C1) (there is only one OpenBSD probe so far)
