### ISSUE TITLE
Provide "drag and drop to install" function for appimage files

### ISSUE THREAD

**Issue by louies0623** [helloSystem/hello#193]
Provide this window as a simple interface for Appimage file installation on the system.(If supported Appimage)

 <img width="500" alt="2739686-11" src="https://user-images.githubusercontent.com/44593430/125173688-04470d80-e1f3-11eb-9cb5-3d7657000595.png">

**Comment by probonopd** [comment]
Unlike dmg files, AppImages execute the payload application automatically when they are double clicked. There is no need to copy the content of an AppImage. It is like if you are running an application directly from the mounted dmg, but automatically. Imho, this is better (and simpler).

**Comment by louies0623** [comment]
Yes, you are right, but I hope it can "install" (actually copy the Appimage file to the application) and display the software on the system menu.

**Comment by louies0623** [comment]
My idea is that if you click on the Appimage file on the file window, a notification will pop up saying "This file is an Appimage file, do you want to install it", and then a window like the one above will pop up. If it is executed directly, it will not  Installation is to double-click the right button to directly execute the Appimage.

**Comment by linuxkettle** [comment]
You can drag it into your Applications folder yourself.

The only reason apps are distributed in DMGs is that you can not upload folders to the Internet.

**Comment by louies0623** [comment]
What I mean is not to execute dmg, but to apply the concept of dmg installation method to Appimage.

**Comment by probonopd** [comment]
You can drag and drop them into e.g., `/Applications` if you like.
