### ISSUE TITLE
Fix Appimage unable to start issue

### ISSUE THREAD

**Issue by louies0623** [helloSystem/hello#195]
When using Appimage, it will appear "usr/local/bin/runappimge ./AppRun not found" notification.

**Comment by probonopd** [comment]
Please file a [bug report with all the required information](https://github.com/helloSystem/ISO/issues/new?assignees=&labels=bug&template=bug_report.md&title=). Thanks!

**Comment by louies0623** [comment]
[PC-2-screen0.webm](https://user-images.githubusercontent.com/44593430/207753416-9419048f-66a2-437c-acd6-1fe1dfa8fe7e.webm)
