### ISSUE TITLE
Hi,May I ask why the hello system ui style is the old macos style?

### ISSUE THREAD

**Issue by Yakumo-Yukari** [helloSystem/hello#198]
Hi,May I ask why the hello system ui style is the old macos style? I mean, why not use Mojave or Big Sur style?

**Comment by Yakumo-Yukari** [comment]
I mean maybe it would be better to use Mojave or Big Sur style

**Comment by probonopd** [comment]
Hello @Yakumo-Yukari. I think Mac OS X visually was best around 10.3-10.4. When buttons still looked like buttons and not just "flat".

**Comment by linuxkettle** [comment]
Agreed. I also like the wooden effects of Tiger.
