### ISSUE TITLE
Match windows to their .app bundles

### ISSUE THREAD

**Issue by probonopd** [helloSystem/hello#199]
Currently there is no easy way to find out which application bundle a given window belongs to. In fact, there seems not even to be a simple way to find out which executable a given window belongs to.

We need to change this, so that we can e.g., retrieve the matching icon or application name for agiven window from the application bundle.

cc @mszoek

---

LD_PRELOAD can be used to set custom WM_NAME properties on applications' windows.

Can we use that to match windows to their .app bundles?

https://github.com/dasJ/spotifywm/blob/master/spotifywm.cpp

**Comment by probonopd** [comment]
Even easier:

```
RESOURCE_NAME=xxxxxxxxxxxxxxxxxxx  /Applications/FeatherPad.app/FeatherPad
```

Results in `xprop` showing:

```
WM_CLASS(STRING) = "xxxxxxxxxxxxxxxxxxx", "FeatherPad"
```

And e.g., Menu picks the first one up:

```
probono: WM_CLASS "xxxxxxxxxxxxxxxxxxx"
```

**Comment by probonopd** [comment]
```
RESOURCE_NAME=/Applications/FeatherPad.app launch FeatherPad
```

works: We get `/Applications/FeatherPad.app` as the first `WM_CLASS(STRING)`.

**Comment by probonopd** [comment]
Possibly we can use this mechanism to keep the launch animation for an application in the Dock running until the first window with the same `WM_CLASS` appears.

**Comment by probonopd** [comment]
Apparently this does __not__ work for Gtk apps:

```
RESOURCE_NAME=xxxxxxxxxxxxx launch /usr/local/bin/system-config-printer
```

Aaaargh!

**Comment by probonopd** [comment]
Somehow KDE managed to hack in its own properties:

```
_KDE_NET_WM_APPMENU_OBJECT_PATH(STRING) = "/MenuBar/2"
_KDE_NET_WM_APPMENU_SERVICE_NAME(STRING) = "org.kde.plasma.gmenu_dbusmenu_proxy"
_KDE_NET_WM_ACTIVITIES(STRING) = "00000000-0000-0000-0000-000000000000"
```

So (how) can we hack in something like `_APPLICATION_BUNDLE` or even `_APPLICATION_EXECUTABLE`?

**Comment by probonopd** [comment]
`_NET_WM_PID` as defined by EWMH seems to come close?

**Comment by ls0h** [comment]
This is the very same problem that caused me to drop development of my DockBarX (dock panel for Linux) many years ago, It took too many workarounds for everything to work properly. There is no way to find a creator of some window in terms of X11 protocol. There was a whole separate daemon for this task in Ubuntu - BAMF daemon. I'm not sure if it is still exists nowadays, or some another replacement has been made for this component. I think it is much better to solve this problem from the `launch` command, like set environment variable on the start. Probably for this you will need to introduce some restrictions, for example, no wrappers, only real applications inside their `.app` directories. 

Can we move (or pkg install) all applications to their `.app` directories? Is it possible? If it is not possible due to changing paths, is it possible to use Jail (or something like that) to trick `pkg install`. I don't know if mount namespaces exist in FreeBSD.

**Comment by probonopd** [comment]
The way I envison it:

* Every GUI application on helloSystem is supposed to go through the `launch` command
* The  `launch` command, before actually executing the GUI application, is responsible for setting the metadata on the process
* The only question is how to do this. Looks like using `LD_PRELOAD` might work universally (but is an ugly overhead) so I am looking for an easier way

**Comment by linuxkettle** [comment]
Well, if you had some sort of manifest file in the app bundle, like info.plist, then you can add a window manager class property that launch reads and tells the dock about. You can also have localised app names.

**Comment by ls0h** [comment]
>The way I envison it:

You can simply set an environment variable (e.g. `APP_PATH`), and force all applications to be placed in their `.app` directories and forbid other behavior. Or use something like Jail for each application, so the application will be in its own directory inside `/Applications`, but at the same time will see itself in `/usr/local`. In the second case, it will be possible to use all applications without breaking compatibility. They will behave as installed with `pkg install`.

In addition, if I understand correctly how macOS works, the application may be running, but not have any windows, just an icon in the dock. Accordingly, if you want to implement such behavior, then you cannot rely on the X11 related protocols, like EWMH.

**Comment by probonopd** [comment]
> You can simply set an environment variable (e.g. APP_PATH), and force all applications to be placed in their .app directories and forbid other behavior. 

I don't want to have this restriction because it would render all "placeholder app bundles" unusable.

> In addition, if I understand correctly how macOS works, the application may be running, but not have any windows, just an icon in the dock. Accordingly, if you want to implement such behavior, then you cannot rely on the X11 related protocols, like EWMH.

Ideally, we would attach our metadata to processes (PIDs). Windows can be resolved to PIDs easily.

**Comment by linuxkettle** [comment]
Can't ps find the parent process?

**Comment by probonopd** [comment]
`launch` is now setting `LAUNCHED_EXECUTABLE` and `LAUNCHED_BUNDLE`.

**Comment by probonopd** [comment]
> Can't ps find the parent process?

How would that help?

**Comment by linuxkettle** [comment]
You keep going up the tree, to the parent of the parent and so on until you reach an AppRun.

Environment variables are probably cleaner.

**Comment by probonopd** [comment]
Using environment variables set by `launch` now.
