### ISSUE TITLE
Check qtfm/draco as a starting point for the desktop

### ISSUE THREAD

**Issue by probonopd** [helloSystem/hello#2]
Can we turn qtfm/draco into the missing hello Filer and hello Desktop described on https://github.com/probonopd/hello/wiki#what-needs-to-be-built?

Reference:
https://github.com/probonopd/draco/releases/tag/continuous

**Comment by rodlie** [comment]
Note that I have not done a lot to draco/qtfm in a while, but my plan was to start working on draco/qtfm this summer again. There are some missing features and a couple of bugs, but IMHO a simpler/better starting point compared to Lumina (no disrespect).

**Comment by probonopd** [comment]
Yes, simple is what I am looking for. Maybe you'd like to have a look around [here](https://github.com/probonopd/hello/wiki) to see whether you think it could be a good fit.

**Comment by probonopd** [comment]
After having experimented with qtfm/draco for a while, I like what I see. It is actually the first desktop and file manager that is not ancient and seems straightforward for my taste.

It appears that @rodlie is sharing a lot of my design philosophy, which is centered around
* "Less, but better" (Dieter Rams)
* Easy
* Not bloated

It seems that in its current form qtfm/draco is mainly appealing to users who grew up in a Windows world (without attempting to clone Windows) with some Unix-isms liek Alt-F2 thrown in. It shows in things such as
* Icons on the desktop are ordered on the left-hand side
* Start menu in the bottom left
* No global menu bar
* Window chooser at the bottom of the screen
* Clock in the bottom right
* Default (OK) buttons on the left in dialog boxes
* Zeroconf nowhere
* Keyboard shortcuts: Ctrl key for commands
* Default iconset from Gnome
* Default fonts from Linux

As you can tell from this project, I would like to create something that is appealing to users who grew up in an early Mac world (without attempting to clone the Mac). This would imply
* Icons on the desktop are ordered on the right-hand side
* Start menu merged with current Alt-F2 functionality and invoked with Alt-Spacebar
* Menubar at the top of the screen, ideally we move the application menus up there (like Ubuntu Unity could do)
* What is currently in the bottom right of the screen moves to the upper right
* Clock in the upper right
* Default (OK) buttons on the right in dialog boxes
* Zeroconf everywhere (e.g., show servers in the file manager)
* Keyboard shortcuts: Alt key for commands
* Default iconset from elelmentary-xfce
* Default fonts URW35

This could further mean little cosmetic touches such as
* Rounded rects in the screen corners

Overall, not technically radical changes, but a distinctively different look and feel.

Generally I am opposed to making everything configurable, or else you basically end up with KDE. if it was just for myself, I would hardcode the Mac-like paradigm just like currently the Windows-like paradigm is hardcoded.

At the same time I realize that forking for just those (little) things may not be a good idea, as it would mean duplicating a lot of (maintenance) work.

So I am wondering @rodlie whether we could add a "paradigm" switch to qtfm/draco that would basically switch between the 2 paradigms.

**Comment by probonopd** [comment]
Check out https://github.com/helloSystem/.
