### ISSUE TITLE
Clarification about touch interfaces

### ISSUE THREAD

**Issue by kingemir** [helloSystem/hello#200]
In https://github.com/helloSystem/hello/wiki/Welcome-and-unwelcome-technologies you write: 
_Touch: The desktop system will be a workstation for productive work, and be entirely mouse-centric. Touch interfaces are for light media consumption, not for productive work_
I would like you to clarify if you consider touchpads (with multi-touch functionalities) also part of "productive" tools. I do. When I switched from a Mac Pro to a MacBook Pro, I quickly learned to switch from the mouse to the touchpad. I never felt being less productive with the Mac Touchpad. I can almost say the same thing about using the touchpad in GNOME. 
My proposition for changing your text would be:
_Touch: The desktop system will be a workstation for productive work, and be entirely mouse/touchpad-centric. Touch screens are for light media consumption, not for productive work_
I wish strongly for hellosystem to have decent multitouch support as Macs do. I work sometimes in the train, in the garden or on a couch. Even in the office I mostly forget to plug in the mouse.

**Comment by probonopd** [comment]
helloSystem is made for mouse operated devices and follows https://dl.acm.org/doi/book/10.5555/573097.
In my experience pixel-precise work is not possible with (most) touch based devices.
