### ISSUE TITLE
Add a way to set wallpapers from Unsplash a site with images under creative-commons licence.

### ISSUE THREAD

**Issue by alphamodh0** [helloSystem/hello#206]
My idea is about a daily wallpaper or an auto-change wallpaper like Bing Wallpaper in Microsoft Windows (I do'nt like Windows, but I like some features).

 Site link: https://unsplash.com

**Comment by kettle-7** [comment]
cc @jhjacobs
we could use that ;~)

**Comment by kettle-7** [comment]
cc @jhjacobs81
we could use that :~)

**Comment by probonopd** [comment]
This would be a nice task for a third-party application. Hence closing here.
