### ISSUE TITLE
Add RTL as part of HIG

### ISSUE THREAD

**Issue by yarons** [helloSystem/hello#211]
Hey, I translated helloSystem to Hebrew, this language is written from Right-To-Left (hence RTL) and requires special care in some cases (Sometimes flipping everything just works).
Additional languages that use an RTL script: Arabic, Persian, Urdu, Divehi, N'Ko, Yidish, etc.

There are numerous documents about taking special care of some individual cases in RTL, for example:
https://engineering.atspotify.com/2019/04/15/right-to-left-the-mirror-world/
https://material.io/design/usability/bidirectionality.html
https://developer.apple.com/design/human-interface-guidelines/right-to-left/overview/introduction
https://community.pega.com/knowledgebase/articles/user-experience/85/converting-your-ui-right-left-languages

I need to free some space for the VM, I want to test it and see that everything is in place.

**Comment by probonopd** [comment]
Hello @yarons. Thanks for contributing translations. Highly appreciated.
Do you know what specifically would need to be done in helloSystem to make it support RTL properly?

**Comment by probonopd** [comment]
Qt

**Comment by yarons** [comment]
https://doc.qt.io/qt-5/qtquick-positioning-righttoleft.html

This is purely technical, the visual stuff are the other links I've sent earlier.
There are some older guides for Qt 4.8 etc. I don't think it's relevant anymore.

**Comment by probonopd** [comment]
Would be interesting to see how far off we are currently. What is your overall assessment of our 0.6.0 ISO?

**Comment by yarons** [comment]
Regarding the HIG or the translation?

**Comment by probonopd** [comment]
My question is, if you run the 0.6.0 ISO, what is wrong/needs to be done so that everything is correct? (Screenshots of places where things are wrong and a description of how they should be would help.)

I'd welcome pull requests that improve things, as long as they won't introduce undue code complexity/overhead. But since I don't know what needs to be done and how, I won't be working on it myself.

**Comment by yarons** [comment]
These are usually changes in the .ui files, I'm not sure how these are handled when you switch the language but I'll try to investigate it with you.

If you can take some screenshots it will surely save us some time.
I think that if it might delay the release we will do our best to aim for the next one, Hebrew users can wait :)

**Comment by yarons** [comment]
I managed to load the ISO in VirtualBox, I managed to make it work but couldn't install it (It keeps failing and restarting), I couldn't find where to switch the language of the UI, I can keep trying but it doesn't look good so far, any suggestions? Should I simply wait for 0.7.0?

**Comment by probonopd** [comment]
Yes. Or you could use 0.6.0 which is the currently released version.

**Comment by yarons** [comment]
Well, without switching the UI language or installing to the local hard drive I'm not sure it's relevant to what we actually want to test :)

**Comment by probonopd** [comment]
0.6.0 can be intstalled to the local hard drive.

**Comment by yarons** [comment]
I've tried, I got into a boot loop with VirtualBox.

**Comment by probonopd** [comment]
I never test anything on virtual machines, only on real hardware.

**Comment by louies0623** [comment]
I think this is the screen that their language should be, the interface and the beginning of the text are reversed, except for the picture and the text.
![image](https://user-images.githubusercontent.com/44593430/208238771-7dbe1a0d-8481-4441-b561-268546300d97.png)

DEMO...
![VirtualBox_PC-2_17_12_2022_18_48_34](https://user-images.githubusercontent.com/44593430/208238268-f1758331-264e-410f-8674-8d6f053c14c7.png)

**Comment by probonopd** [comment]
Not sure whether the whole screen should be flipped just because the language is LTR. I don't think this is how other desktop OSes are doing it?

In any case, this is currently not a priority, no one is working on it.
Can be reopened in case anyone wants to work on it.

**Comment by louies0623** [comment]
> Not sure whether the whole screen should be flipped just because the language is LTR. I don't think this is how other desktop OSes are doing it?

- Mac OS [image](https://user-images.githubusercontent.com/44593430/208247026-26de5c6d-6f48-4191-ade7-77a77f374138.jpeg)

- Windows [image](https://user-images.githubusercontent.com/44593430/208247003-83d1734c-d01f-4a0a-8ff5-51972dfd69b5.jpeg)

**Comment by probonopd** [comment]
Wow. It's not something I'm looking forward to doing; so this would only happen if we find a volunteer who wants to do it.

**Comment by yarons** [comment]
I was referring to the HIG, not the actual desktop directionality and I'm not sure why Hebrew is not part of the language set, it is fully translated.

**Comment by probonopd** [comment]
We are merely pointing to https://dl.acm.org/doi/book/10.5555/573097, there is no helloSystem HIG currently.

**Comment by probonopd** [comment]
>  I'm not sure why Hebrew is not part of the language set, it is fully translated.

It would probably need more work, e.g., a better font, more RTL work, etc.

**Comment by yarons** [comment]
> We are merely pointing to https://dl.acm.org/doi/book/10.5555/573097, there is no helloSystem HIG currently.

There are RTL references in this HIG, just search for Hebrew or Arabic and you'll find it.

Is there an open issue about the font and RTL work so I can try and help with it?

**Comment by louies0623** [comment]
46/418 inPDF https://dl.acm.org/doi/book/10.5555/573097

**Comment by yarons** [comment]
@louies0623 indeed, so @probonopd, this issue was never relevant in that case, we just need to work on the issues with Hebrew display in terms of fonts and RTL then.

**Comment by probonopd** [comment]
Newer is not always better :)

**Comment by louies0623** [comment]
@probonopd I think you can ask him about the text font first.

https://github.com/helloSystem/hello/issues/445

**Comment by yarons** [comment]
@louies0623 I will definitely work with you on that one, what is the license limitations so I won't offer any irrelevant options.

**Comment by probonopd** [comment]
Font should be a "real world" font, not a "computer" font. Ideally should look like Helvetica.

License needs to have no restrictions on redistribution.

**Comment by yarons** [comment]
> Newer is not always better :)
> 
> The one I linked was being worked on by [Tog](https://asktog.com/) and other legends.

Although I do ten to agree in a way I find myself thinking about designing a system with a closed system loop as opposed to open feedback when some lessons have learned and the users are more demanding and reflect different usage patterns.
I totally think his work rocks yet many things have changed along the years and back in 1992 there were fewer users and fewer options and it did affect the user's usage patterns and perspective.
Just my two cents, thanks.

**Comment by probonopd** [comment]
Note that I also didn't say "older is _always_ better" ;-)

**Comment by yarons** [comment]
I appreciate that, thank you :)

**Comment by louies0623** [comment]
There should be a "help wanted" tag so someone knows this needs help.
As an aside, our Chinese used to be right-to-left like Hebrew, but it was changed about 60 years ago.

**Comment by louies0623** [comment]
@probonopd 
I tested it a little on your Ubuntu test version. It has been changed, but the notification icon and window list menu position need to be fixed.
![20230925_213544](https://github.com/helloSystem/hello/assets/44593430/afc5dcb2-a5b5-4406-a7cb-ef2af7a6657a）
![20230925_213310](https://github.com/helloSystem/hello/assets/44593430/44ed260d-ef26-4700-a896-2523000bffa6)
“System menu”
![20230925_213534](https://github.com/helloSystem/hello/assets/44593430/eeae3fab-7c84-41f7-baa5-99d296f94b23)
“Window list menu”

**Comment by probonopd** [comment]
RTL languages are currently not supported in helloSystem. To make them work properly, more than just translations would need to be done, e.g., automatic on-demand installation of RTL fonts if needed,  changing the layout of the Menu and probably some dialog boxes, etc. To do this correctly we would need some developer who is familiar with at least one RTL language, knows what to expect in terms of user interface layout, and would be willing to do the work.

For exammple, the KDE screenshot in this thread shows that most things are left-to-right but not all are, e.g., the panel at the bottom of the screen is not. I am also not so sure whether the alignment of interface elements shown in Figure 2-2 on page 45 of the HIG is what a HIG speaker would expect. Shouldn't the default button all the way to the left? How is it on today's macOS?

I cannot not do this work since I don't speak any RTL languages, and I don't know how things should work in RTL languages. If someone would like to make the necessary changes, I'd be happy to discuss.

Right now we are foc
