### ISSUE TITLE
About This Computer on custom/self built PCs

### ISSUE THREAD

**Issue by lillycat332** [helloSystem/hello#216]
On a built/non OEM machine since the about this computer box reads from the oem information in DMI table from uefi so it just shows "To Be Filled By O.E.M. To Be Filled By O.E.M." which isn't particularly good looking or helpful, maybe it could display "custom pc" OWTTE, or maybe an option to use hostname or a custom name?

**Comment by louies0623** [comment]
At least provide a UI for people to set.

**Comment by probonopd** [comment]
I think this needs to be set with vendor-specific tools coming from the mainboard manufacturer or firmware ("BIOS") manufacturer. Those are often DOS or Windows based and proprietary (used in production). I don't know a tool which can set this for all kinds of hardware.
