### ISSUE TITLE
HelloSystem is finally 100% translated into Spanish!

### ISSUE THREAD

**Issue by alphamodh0** [helloSystem/hello#251]
HelloSystem is finally 100% translated into Spanish! I was worried that I couldn't help because I didn't know much about programming, but I'm happy that I was able to do something 😁.

**Comment by probonopd** [comment]
This is great to hear @alphamodh0 - thank you very, very much! :+1: 
Be sure to download the latest experimental ISO to check out that your translations have arrived there.
Keep it up!

**Comment by probonopd** [comment]
Would you like to be named on https://hellosystem.github.io/docs/developer/acknowledgements?

**Comment by alphamodh0** [comment]
I would feel very happy 😁

**Comment by probonopd** [comment]
It's my pleasure.
