### ISSUE TITLE
Themes (Make black theme and make better actual theme)

### ISSUE THREAD

**Issue by alphamodh0** [helloSystem/hello#256]
Could you tell me where helloSystem themes and stylesheets are stored? I would like to make the theme dark and touch up the current theme, that with your permission and my greatest admiration for you. Keep trying! 👍🏼😁

**Comment by probonopd** [comment]
Hello @alphamodh0 please familiarize yourself with the [HIG](https://hellosystem.github.io/docs/developer/ux-guidelines) before you proceed to doing anything.

Then, have a deep look at https://github.com/helloSystem/QtPlugin/blob/master/stylesheet.qss which resides at `/usr/local/etc/xdg/stylesheet.qss` on the helloSystem ISO. You can make changes there (as root), save it, restart an application and see it in effect.

But beware that not all aspects can be controlled this way. Some need to be changed in https://github.com/helloSystem/QtPlugin/ but I am still learning how all of this works myself.

Have fun! But please be aware that we have very specific objectives for this project and will reject change requests unless they help fulfill our project mission. A dark mode is very unlikely to make it into the system anytime soon, for example.

**Comment by alphamodh0** [comment]
Speaking on the subject you may be right, the system is not yet complete and a dark theme should not be among the priorities.

I think there are tweaks that should be made in the interface, when I use my laltop again, I will write what I have noticed that it does not fit.

**Comment by probonopd** [comment]
Please feel free to send improvements as pull requests. Thanks!
