### ISSUE TITLE
FreeBSD USB Quick Formatter ---> USB Formatter.app

### ISSUE THREAD

**Issue by alphamodh0** [helloSystem/hello#261]
Link will work around a week, please update the app to Repository if you like it: https://www.filemail.com/d/dvlrwonlqyufqcr.

**Comment by probonopd** [comment]
Interesting. Should have known this a couple of weeks ago.
Have developed this kind of thing myself:
https://github.com/helloSystem/Utilities/tree/master/System/Format%20Disk.app

Thanks for sharing, anyway.

**Comment by alphamodh0** [comment]
Never mind, I have learned quite a bit about .app bundles and some python code. In case I achieve improvements, do you think I can send them for you to take a look?

**Comment by probonopd** [comment]
Sure! I'd be happy to see pull requests on my code. Especially if they address the lines marked with "FIXME" or "TODO".
