### ISSUE TITLE
First problems in my helloSystem instalation.

### ISSUE THREAD

**Issue by alphamodh0** [helloSystem/hello#262]
My experience with helloSystem as a Linux user for a long time:
One of the things that surprised me was that the ntfs and ext4  drivers were not installed, so I had to give myself the task of testing ntfs-3g and. My opinion is that all possible file systems should be covered.
The other thing that did not seem correct to me was that the compatibility layer with linux was not pre-installed or activated by default, so I had to activate kernel modules, download packages and learn new commands (which does not seem strange to me as a linux user , but it was a problem for a normal user like my dad.)
The last thing I'm going to comment on is that we need a simple graphical interface to install missing drivers and utilities without being a driver expert, something like mint-report from the Linux Mint Project.

**Comment by probonopd** [comment]
Hello @alphamodh0, which drivers (packages) exactly do you mean with "ntfs and ext 4m drivers"? Drivers for NTFS and Linux ext are preinstalled and preconfigured on helloSystem.

Regarding Linux, I really recommend https://github.com/mrclksr/linux-browser-installer. Not only will it set up the Linuxulator, it will also set up a Ubuntu based userland which helps compatibility a lot in my experience.

**Comment by alphamodh0** [comment]
Sorry, I had spelling mistakes. Regarding the drivers, the pendrive I had in NTFS was not automatically mounted. In the end I had to format it (I really don't care about the format) but it could cause data loss or very uncomfortable situations.

Thanks for the tip on Ubuntu chroot, it looks promising.

What do you think about having a GUI to install the drivers (for example video: which I had to install because the default ones slowed down when playing videos)?

**Comment by probonopd** [comment]
> Regarding the drivers, the pendrive I had in NTFS was not automatically mounted

That would be a bug. NTFS volumes should be mounted automatically. Please look at `/var/log/automount.log` and search for NTFS. Do you see any errors there?

> video: which I had to install because the default ones slowed down when playing videos

What exact driver did you have to install, how did you install it?

> What do you think about having a GUI to install the drivers 

This is nothing the user should have to worry about. GPUs and other hardware should be automatically detected by the system, and the best available driver should be used automatically. If additional work is currently needed, then it is a bug.

**Comment by alphamodh0** [comment]
I am running a Intel HD Grafics 3000, I use i915 driver:
From: https://wiki.freebsd.org/Graphics
Install the graphics/drm-kmod package

# pkg install drm-kmod

The post-installation message presents essential information. With FreeBSD 13⋯, this command will safely configure your /etc/rc.conf:

# sysrc -f /etc/rc.conf kld_list+=i915kms

Ensure that your UID is a member of the video group.

Restart your system. You should see i915kms listed, and a flash of the console when the display driver is switched.

Start X.Org via your usual method (i.e. startx, GDM, etc.)

**Comment by alphamodh0** [comment]
Your browser is also slow ?, When I navigate in certain situations it becomes unbearable. Especially Falkon. Could it be the graphical acceleration?

**Comment by probonopd** [comment]
`initgfx` should be loading the `915kms.ko` automatically on systems with an Intel GPU. I just tested this with the latest experimental 0.7.0 ISO. It does work for me.

Please boot the latest experimental 0.7.0 ISO, then run Terminal, enter: `kldstat | grep 915`

What does it return?

**Comment by probonopd** [comment]
Relevant code is at:

https://github.com/helloSystem/ISO/blob/41f68ee81af710c02b761821de22942222517bf8/overlays/uzip/initgfx/files/etc/rc.d/initgfx#L253-L269

**Comment by alphamodh0** [comment]
I live in a country where the internet is a problem, but I will try to see in image r 0.6 how to autoload the 915kms.ko module

**Comment by alphamodh0** [comment]
915kms is working (I can see videos correctly) to me but browser experience is bad.

**Comment by alphamodh0** [comment]
Sorry for the little collaboration lately. I am trying to be an active contributor but some personal things take my time. Thank you for answering all my questions and taking my opinion into account.

**Comment by probonopd** [comment]
What _exactly_ do you mean by "browser experience is bad"? Without a clear description of what is not working properly there is little we can do to improve it.
