### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by alphamodh0** [helloSystem/hello#263]
My father today started using my laptop for certain jobs. Any way to install the translations made in weblate without changing helloSystem 0.6 or reinstalling the system?

**Comment by probonopd** [comment]
@alphamodh0 the translations should be on the ISO already. Which translations are you missing?

**Comment by alphamodh0** [comment]
The system never asked me during the installation the language I wanted to use and I cannot find in configuration any way to change the language (keyboard only) and since I speak Spanish and I have an English keyboard, I use en-US with dead keys in Alt-Grnd

**Comment by alphamodh0** [comment]
¿Any way to configure language?

**Comment by probonopd** [comment]
Currently two ways are implemented:
* On Macs, the language from the EFI variable set by macOS is used. Once https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=251025 is fixed it will be possible to write this EFI variable from within helloSystem
* Using a Raspberry Pi keyboard, the correct language for the keyboard and the system will be set automatically based on the language of the keyboard

**Comment by kettle-7** [comment]
So on neither pi keyboard nor mac there is no way to change it for 'mere mortals'

**Comment by alphamodh0** [comment]
I would prefer a standard setup menu one way: Menu, Change Language, Spanish. Menu, Change Keyboard, Spanish. In addition to that it would allow to select a keyboard different from the spoken language, or to select varieties of keyboards.
