### ISSUE TITLE
Help (now fixed)

### ISSUE THREAD

**Issue by alphamodh0** [helloSystem/hello#274]
After a few proofs on my laptop (install a linux distro to help a friend) I want to back to helloSystem. I have a Ventoy USB with 0.6.0 release (same I installed before) but now, when i try to install ![20211209_082002.jpg](https://user-images.githubusercontent.com/90866187/145404573-175ff390-7927-4520-ba9a-450de947b578.jpg)this boot splash does'nt go never.

**Comment by alphamodh0** [comment]
¿Any way to see whats happening?

**Comment by probonopd** [comment]
Please retry with a 0.7.0 experimental ISO. The Ventoy work went into 0.7.0.

**Comment by probonopd** [comment]
Please boot in verbose mode. It is described in the documentation. Thanks!

**Comment by alphamodh0** [comment]
![20211209_151020.jpg](https://user-images.githubusercontent.com/90866187/145468511-60f44a25-b3d6-46f2-a2cf-d41266abedc7.jpg)

**Comment by probonopd** [comment]
It doesn't find the ISO. Please give more details:
* Live or installed?
* Exact build number of the ISO
* Your hardware
