### ISSUE TITLE
Downloadable Centralized Apps

### ISSUE THREAD

**Issue by alphamodh0** [helloSystem/hello#276]
I see your Youtube videos, medium publications and tweets. After reading the medium serie about linux usability i guess we need the ipfs system to make downloadable apps like appears in your youtube videos. (I want to install some of your apps) And we can start making a kind of peer-to-peer syatem to share but centralized database.

**Comment by probonopd** [comment]
Something like this?

![image](https://user-images.githubusercontent.com/2480569/145692229-e6e03e72-1925-4216-880f-41228deb3474.png)

**Comment by alphamodh0** [comment]
That's what I was talking about! Its beautiful. I think you should have some way to see the icon of the application you want to download and also metadata about it (Description, Authors, etc ...). Thanks for your brilliant work. Things like that make me proud to use HelloSystem.

**Comment by alphamodh0** [comment]
I am interested in obtaining it. Any way?

**Comment by probonopd** [comment]
It will be in the next experimental build.
