### ISSUE TITLE
Chromium can't install extensions or themes.

### ISSUE THREAD

**Issue by alphamodh0** [helloSystem/hello#281]
![chromium error](https://user-images.githubusercontent.com/90866187/145689808-eee745ca-a710-4492-a4bb-48b79d790b0f.png)

**Comment by probonopd** [comment]
Please post errors with the ISO here:
https://github.com/helloSystem/ISO/issues/new/choose
In your ticket, please explain where you got that Chromium onto your system, as we have at least 4 different ways now ;-)

Thanks!
Without the necessary information it is hard to do anything.
