### ISSUE TITLE
About Wayland

### ISSUE THREAD

**Issue by DragonSWDev** [helloSystem/hello#29]
Hello.

First I want to assure you that I generally share your opinion. I love AppImage, it's very nice way to distribute package which reminds me ".app" bundle from macOS where I can easily install/remove/move applications by simply dragging their icon. Second I agree that Linux userland (kernel itself is fine in most cases) sometimes can be very annoying mess for user or developer. I really like your ideas to make operating system easier and FreeBSD is such a great project. But there is one thing I want to discuss with you - your claims about Wayland.

When I have read Wiki and saw your claims against Wayland - I can't really agree with them. Let me refer to your document called "Boycott Wayland. It breaks everything!".

> Wayland solves no issues

Are poor HiDPI (especially with mixed DPI) support, poor multi GPU support, complicated displaying (tearing, flickering etc.), security issues (every client can easily read input/ouput of another client) or maintenance problems (as stated by Xorg developers) not issues for you? You seems to ignore the fact Wayland isn't by some developer who think he can make desktop Linux better but by some Xorg developers knowing Xorg issues and need for replacement. Do you ignoring these problems by saying that Wayland solves nothing?

> It breaks everything!

"Everything" in this case means just "global menu", "screen share" and "screen recording". Is this really "everything"? Especially the fact these features are not "broken" but works differently.

> because the Wayland folks only seem to care about Gnome

Why do you think so? Just because GNOME has probably best Wayland support is equal to "Wayland cares only about GNOME"? Wayland is not focused on any desktop and can be extend to other needs. For example look at "xdg_decoration_unstable_v1" interface. It's a interface used by compositors to announce support for server-side decorations which applications can used. As we probably all know, GNOME developers are against server-side decorations and supports only client-side decorations. This protocol is official Wayland interface and in fact it's heavily based on interface created by KDE developers. If "Wayland cares only about GNOME" why did they accepted interface created by KDE developers that is very against GNOME developers vision?

> Or force more Red Hat/Gnome components (glib, Portals, Pipewire) on everyone!

Again what makes them only GNOME or Red Hat solutions? Let me talk about Pipewire. Is somewhat similar to PulseAudio but extended to video (in fact first name of this project was "PipeVideo"). It supposed to make standard way to implement things like screen share or screen record and unify solutions like JACK or PulseAudio. Of course you can say that these things are working on Xorg just fine and it is true. But how does they working? Simply by grabbing clients outputs as Xorg permits such thing. Do you really think its correct way to do it? Do you think its fine that every application can simply grab output without even asking? With PipeWire it's not that obvious. Applications need permission to do that. If you try screen share on Wayland with PipeWire you can see that its actually asks you if you want to share screen. It's way more secure than Xorg ever was. Also portals are supported by KDE (xdg-desktop-portal-kde) and wlroots based compositors (xdg-desktop-portal-wlr) so argument like "This is Red Hat/GNOME solutions" is simply invalid.

> Wayland breaks global menus in Gnome

Global menu are not and never was supported in GNOME 3 or GTK+3. You are talking about unofficial extensions. It's GNOME developers decision to not support it, not Wayland issue. Now if you look at KDE, where global menu are supported feature, it's working on Wayland. You posted link to KDE bugzilla with issue that is currently solved. So how this can be Wayland issue? 

> Wayland breaks AppImages that don't ship a special Wayland Qt plugin

This is again not Wayland issue. It's how the Qt plugins actually works. If desktop are working on Wayland then Qt wants to use Wayland plugin and it's definitely good idea. What is bad is the fact that if such plugin are not existing or it's broken then Qt applications simply won't run. It would be nice if Qt would fallback to Xorg but it's a Qt problem, not Wayland. You will get same issue on Windows if you won't provide Windows plugin or in macOS if you won't provide macOS plugin. Also I can't see why Wayland plugin can't be distributed with AppImage application. 

Of course I'm not saying that Xorg is garbage and Wayland is perfect. Both has advantages and disadvantages. As for Wayland disadvantages I can mention pretty poor support compared to Xorg or complicated situation with drivers (EGLStreams vs GBM). Also solutions like PipeWire and portals should be available sooner to make things like screen share, screen recording or even screenshoots work years ago. But saying that "Wayland solves nothing and just breaks everything" is simply not true. And it's not like somebody told this, even Xorg developers are aware of this and that's why they developing Wayland. Especially if you appreciate macOS because macOS display stack is much more similar to Wayland than to Xorg. 

Greetings to you and thank you for your work!

**Comment by probonopd** [comment]
Hi @DragonSWDev, thanks for taking the time to share your thoughts. I appreciate your input and I certainly hear from many sides that Wayland has many technical merits, which I don't dispute. All I am saying is that it does not solve issues that _I am currently experiencing_, while it does break a lot of stuff _I need on a daily basis_, including screen sharing.

Until that is fixed, Wayland is not an option for me. (And I think it is not fair to expect application developers to do that work by the way.)

**Comment by DragonSWDev** [comment]
Hello @probonopd 

Thank you for your answer. I think I understand your position better now. 

>And I think it is not fair to expect application developers to do that work by the way.

Yes, I can agree that these things should work from beginning instead of telling developers: "Do it by yourself". We have now PipeWire which I think it's correct way but it should be available sooner. 

>From my observations over the years, certain developers develop for Gnome first and foremost

It's truth but it's also kinda obvious. GNOME is desktop environment backed up by Red Hat probably the most influential Linux company. So no doubt they first target GNOME with their solutions. But I don't think it's big issue as long these standards are portable. Wayland and PipeWire are such technologies. I've mentioned how server side interface was accepted as Wayland standard despite GNOME way which rejects such thing and PipeWire can also work fine on other desktops.

>I do have issues with this as soon as those technologies are then declared "XDG" or "standard", which at that point means that Gnome technology is forced upon everyone

I don't think I would call them "GNOME technology". They were created to solve some problem which is common across whole Linux ecosystem. Wayland was created to solve Xorg limitations. PipeWire was created to make standard way for multimedia processing (and provide standard way to do remote desktop or screensharing on Wayland). As I said before they are portable and don't need GNOME at all. Yes it can be hard for smaller projects to catchup but that is also correct for any new technologies no matter where they were created.

>In fact, for hello I want to become 100% glib-free, if possible.

That looks like a solid reason.

**Comment by DragonSWDev** [comment]
@probonopd Do you think we should close it? It doesn't look like it will be "fixed" (whatever that means in this context).

**Comment by probonopd** [comment]
Thanks @DragonSWDev. Yes I think from the perspective of the hello project we will not be able to switch to Wayland anytime soon because it is not a 1:1 compatible Xorg replacement. Feel free if you think this should be reconsidered at some point (e.g., once apps like Jitsi Meet "just work").

**Comment by DragonSWDev** [comment]
@probonopd Thank you for discussion.
