### ISSUE TITLE
Need a software like MATE Software Boutique to replace the download software on menu

### ISSUE THREAD

**Issue by louies0623** [helloSystem/hello#296]
![image](https://user-images.githubusercontent.com/44593430/146698615-f6f26147-7cfe-41e3-b599-7eda03688302.png)

We need a software download area like MATE Software Boutique as our carefully selected software download area, because it can be concentrated on Software Boutique instead of on the Menu, which makes people think that this is already installed. Another way of saying is, just let the Menu display Software already installed on the system.
It differs from ordinary stores in that the store needs to always introduce hundreds of software and maintain it continuously, while Software Boutique only provides carefully selected software.

There are more instructions on its website: https://ubuntu-mate.org/features/boutique/

**Comment by probonopd** [comment]
In 0.7.0 there is a **Download Applications** utility in the Under Construction folder. By adding some icons and other metadata, it could become similar to this.

**Comment by louies0623** [comment]
I can agree with your opinion on the store, because major Linux or BSD systems such as Ubuntu, GhostBSD or Fedora rely too much on stores to install software, and it’s not as good as moving the downloaded appimage to the Applications folder on Mac OS. Double-click BOOM! The installation is complete and open the software. If you want to remove it, just move the appimage to the trash can. It's as simple as that.

But what I don’t completely agree with you is that you put some "almost pre-installed" on the Menu, which will make users feel very convenient, but it will feel like being promoted in the heart, just like Ubuntu once added Amazon to On the menu, users should find it convenient. In fact, it is the most complained web guide software.
On the other hand, the advantage of having a collection of selections is that it can make users feel that which software I want to download appears on the start menu of my computer is my decision; and when downloading, it automatically leads to the latest version of the software, or you or Other system developers want to add new selected software, as long as they add new options, the installation steps are completed by the procedures set by Software Boutique, so there is no need to develop new download software, which will save a lot of trouble .

**Comment by probonopd** [comment]
I assume that people didn't like the Amazon integration in Ubuntu because it sent their search terms to a server of a commercial company. helloSystem is not doing this. But let's see what other users think about the pre-integrated curated applications.

**Comment by alphamodh0** [comment]
I think software selection is great, we don't have a lot of developera to make our own software (this should be awesome🤩).
