### ISSUE TITLE
An idea for using a different programming language instead of Go

### ISSUE THREAD

**Issue by grd** [helloSystem/hello#301]
Hi Guys, in the past I was a frequent user of Go, but Go always did have some problems, such as that the files are HUGE and the linking can take a LONG time when linking a serious program.

So I searched for alternatives, I am not fond of Rust, and then I found V [1]. When you know Go, then learning V is easy. Because they use roughly the same use and feel of Go, but it has a few benefits such as that the compiled file size is comparable with C, and the linking is fast. You can compare it with C but then SAFE, and the compile time has been drastically reduced. They don't use manual memory management but an intelligent memory management, and they use (afaik) RC once in a while (probably when they use concurrency) but for the rest, the memory cleans itself up. So V is also as fast as C. This is very impressive. Right now they are working on a new linux-like OS (it is in early stages), a new user interface (VUI), but there are also external programs, such as IUP (that I like too a lot [2]).

The cons are:

1. It is not R1 yet (that will take a while, I am afraid).
2. They are working on a C to V transpiler, but that has not been released yet. Of course you can use C for linking and even inside V code (comparable with Go).

All in all it is a PL with the same mind set as yours. They got sick of legacy, thought hard about a solution, and then they implemented it.

[1] https://vlang.io/
[2] https://github.com/kjlaw89/viup

**Comment by probonopd** [comment]
Hi @grd thanks for your suggestions. I will check out V.
Right now we are actually getting away with using Python and Qt for most of our [utilities](https://github.com/helloSystem/Utilities/), as most of the underlaying code has already been written by others in C/C++ and we are just putting GUIs on top.
