### ISSUE TITLE
0.7 install missing important files in /usr/lib (possibly /usr/local/lib?)

### ISSUE THREAD

**Issue by ryanrms** [helloSystem/hello#309]
Hi, I have been trying to compile a Linux app for a bit, and got some help from the #freebsd channel.  They were able to get somewhat further than me because my system (a freshly installed helloSystem 0.7) is missing important glibc runtime files in /usr/lib (or maybe (/usr/local/lib).  The system boots fine and it seems normal besides this.

The files include: crt1.o, crti.o, and crtbegin.o among others, they appear to be standard for compiling C programs.  Were they not included due to a reason or is this an oversight?  Is there any way to obtain them?  Thanks for your help!

**Comment by probonopd** [comment]
`.o`files and other files for developers are not shipped by default to reduce the ISO size. You need to install **Developer Tools** from `developer.img` (for 0.7.0, this is https://github.com/helloSystem/ISO/releases/tag/r0.7.0).
