### ISSUE TITLE
Support for POWER-based Raptor machines

### ISSUE THREAD

**Issue by TCH68k** [helloSystem/hello#315]
Hello guys,

If you're really interested in privacy, then you could check the machines of Raptor; they are all designed and built with privacy in the focus.
x86 is a privacy-crusher in itself, (intel ME, AMD PSP and who knows what else is on our MB-s).

**Comment by probonopd** [comment]
Closing unless someone sends me some POWER-based Raptor machines free of charge and cirrus-ci.com offers free POWER builds.
