### ISSUE TITLE
Change Dark Grey on Light Grey colours in single user mode

### ISSUE THREAD

**Issue by SanPollo** [helloSystem/hello#318]
Please change the light grey on dark grey colour scheme when working in single user mode / using a tty.

It is almost impossible to read and causes eyestrain. I understand that you are trying to preserve the 10.4 look, so you therefore may not want the default dull white on black, but please change the text itself to black so it is clearly visible.

![GreyOnGrey01](https://user-images.githubusercontent.com/6193091/149950441-c13343e9-fad3-4765-bf72-d9f9a9dca67e.jpg)
![GreyOnGrey02](https://user-images.githubusercontent.com/6193091/149950446-17f181bd-4d37-4a0d-9770-f05891e36ba3.jpg)

**Comment by SanPollo** [comment]
@probonopd Thank you for your reply. I am using 0.8.0 but unfortunately I'm finding the text is still very hard to see.

I understand that the focus of helloSystem is on the average user, but I can see myself breaking my installations a lot while testing, so I think providing a pleasant console experience (at least in single user mode) is still important.

Yes, single user mode is only used in an emergency, but yesterday when helloSystem froze on the boot screen after I modified the wpa_supplicant.conf and I had to boot into single user mode, I could hardly see what I was doing! 😄 

I have just had a play around now, and if I type _vidcontrol lightwhite_ in single user mode / into a tty it actually changes the text black (I guess because of the colour scheme you are using).

Would it be possible, in the interests of people like myself who will likely break things a lot while testing, to add _/usr/sbin/vidcontrol lightwhite_ to one of startup scripts? Even if it's just executed in _/etc/rc_ when booting into single user mode? I could also look into this if you agree.

**Comment by defcon8** [comment]
+1

**Comment by probonopd** [comment]
You might want to `unset loader_conf_dirs` at the bootloader prompt, and/or play with `/boot/loader.mute.d/loader.conf`.

**Comment by probonopd** [comment]
Found a way to improve this. Starting with 0.8.1, there is now black text if the user presses "v" (verbose) or "s" (single) during boot at the time when the screen becomes gray.
