### ISSUE TITLE
vi is missing from helloSystem default install

### ISSUE THREAD

**Issue by SanPollo** [helloSystem/hello#319]
Please make /usr/bin/vi part of the default installation for helloSystem as it is with a standard FreeBSD installation.

It's very small and incredibly useful for UNIX-veterans in the Terminal and in single user mode. I understand that nano is installed but it would be nice to have a choice.

I know that Vim can be installed from editors/vim but it is not the same (e.g. it has colours that have to be disabled in a config file), and it is not available on first boot when networking may not be available.

**Comment by probonopd** [comment]
Developer-centric command line tools are not shipped on the Live ISO by default in order to reduce its size. You need to install the Developer Tools if you want `vi` and other developer related command line tools. This is a feature, not a bug.

**Comment by SanPollo** [comment]
@probonopd that makes perfect sense. Thanks for clarifying.
