### ISSUE TITLE
Allow Windows key to be used as CMD key

### ISSUE THREAD

**Issue by SanPollo** [helloSystem/hello#321]
Please implement an option to allow the Windows key to be used as the CMD key.

I understand that Mac users are used to pressing the key to the left of the space bar, but if you plug an actual Apple keyboard into the PC, the key to the left is CMD, and acts as the Windows key when running Windows.

Conversely, if you use a standard PC keyboard with a Mac, then Windows key becomes the CMD key.

Additionally, for me it is confusing as I expect the Windows key to be translated into the CMD key in the Mac / helloSystem world.

[Microsoft Support: Keyboard mappings using a PC keyboard on a Macintosh](https://support.microsoft.com/en-gb/topic/keyboard-mappings-using-a-pc-keyboard-on-a-macintosh-d4fd87ca-8762-30ee-fcde-08ffe95faea3)

![KeyboardLayout](https://user-images.githubusercontent.com/6193091/149953005-8c8e96e9-18eb-4d87-ad9c-ffb16e6efd9b.png)

**Comment by probonopd** [comment]
> Conversely, if you use a standard PC keyboard with a Mac, then Windows key becomes the CMD key.

...which always struck me as wrong and is the first thing I change when I use a PC non-Apple keyboard on a Mac.

macOS and Haiku have very similar dialogs along those lines - this is relatively straightforward to understand:

![image](https://user-images.githubusercontent.com/2480569/150000742-2b9dfa52-06fd-46ef-b6f0-5819ff3b5c19.png)

However, I don't know how to implement this using the crude underpinnings that we have to work with, namely `setxkbmap`...

**Comment by SanPollo** [comment]
Does the answer in [this link](https://askubuntu.com/questions/29731/rebind-alt-key-to-win-using-setxkbmap) regarding altwin in setxkbmap help at all?

**Comment by probonopd** [comment]
Partially. I don't know how the various "bilateral" switch options mix and match to create something more logical (to me) like the screenshot above.

**Comment by SanPollo** [comment]
Could you maybe have a drop down menu instead that for "Command key" which lets you choose either CTRL, ALT or WIN and whichever one the user chooses, it swaps the two keys?

**Comment by probonopd** [comment]
The trouble begins when you start swapping more than one key... doesn't it?

**Comment by SanPollo** [comment]
I was thinking about this, and in theory, there should only be two scenarios:

1. The user has an Apple keyboard so the CMD key is used as normal, and nothing is swapped.

2. The user has a Windows keyboard, and CMD is swapped with ALT (which is directly left of the space bar). This should probably be the default as more users trying helloSystem will likely have generic Windows keyboards.

This will mean that CTRL can be used as normal in Terminal and command line applications to perform CTRL + C, CTRL + T, etc.

What do you think?

**Comment by probonopd** [comment]
Keep in mind, our objective is that if we sit a longtime Mac user blindfolded in front of a helloSystem machine with either a Mac or PC keyboard, then the user should be able to copy and paste using the "normal" shortcuts without having to look at anything.

So this is what we are doing as of 0.7.0 ([code](https://github.com/helloSystem/Utilities/blob/cc233a6cf7961463b26d9d117a4cc014f8a8ae35/Preferences/Keyboard.app/Keyboard#L242-L249)):

For Apple keyboards:
* Use the ⌘ key for menu shortcuts (this swaps alt and cmd) using `ctrl:swap_lwin_lctl` and `ctrl:swap_rwin_rctl`

For PC keyboards:
* Use the Alt key as ⌘ (this swaps Ctrl and Alt) using `ctrl:swap_lalt_lctl`

> The user has an Apple keyboard so the CMD key is used as normal, and nothing is swapped

Then the ⌘ functionality would not be on the key directy left to the spacebar, where it belongs. Instead it would be on the key labeled "Ctrl". As a result, the keyboard would not behave like long-time Mac users expect.

> The user has a Windows keyboard, and CMD is swapped with ALT (which is directly left of the space bar).

Software compiled for Unix-like systems generally puts shortcuts on Ctrl-something. So if we want the key left to the space bar to have ⌘ functionality, then we need to swap Ctrl and Alt on PC keyboards.

Which means that Ctrl-C is now ⌘C and should be used for Copy.
Which means that Unix-like Ctrl-C Escape needs some other key combination (e.g., an additional SHIFT).

Or am I overlooking something?

**Comment by 9gay** [comment]
doesn't usage of ctrl or alt as command key create conflicts with default key bindings in applications? for example, in my experience different window managers perform window operations in blender when I actually press those keys to change the shape of the models (I'm running hello inside vm, so I can't afford testing for now) which kinda makes me jealous of windows artists who show their tutorials with default key bindings on youtube

**Comment by dszidi** [comment]
Perhaps consider shipping kinto.sh by default. I haven't tried it on FreeBSD but it worked great on Linux and from what I remember the only requirement was X11 (no wayland)

https://github.com/rbreaves/kinto

**Comment by louies0623** [comment]
It's swap Windows and Alt , not the Ctrl and Alt which is exactly what I want to express!! this is what I want to express after testing with mac keyboard.

**Comment by probonopd** [comment]
Is there a `xkbmap` option similar to `ctrl:swap_lalt_lctl` that would do this?

**Comment by louies0623** [comment]
https://github.com/helloSystem/ISO/issues/415#issue-1446593491

**Comment by louies0623** [comment]
No is
Ctrl -> Ctrl (no swich)
Windows -> Alt
Alt -> Windows
![螢幕快照 2022-12-17 下午8 58 42](https://user-images.githubusercontent.com/44593430/208243024-7182d4b7-16f6-4401-a1d9-8bce56ee7892.png)

**Comment by probonopd** [comment]
That can't be it, because then the Command key (as used in helloSystem) would not be left to the space bar at all... If you did it like this, then you would have to press the four keys from the spacebar as the Command button. But the Command button in helloSystem is always supposed to be the button immediately left to the spacebar.

**Comment by louies0623** [comment]
If it can't be solved from the existing one, it should be solved with this one, because it's too confusing.
https://github.com/rbreaves/kinto
![2byg7](https://user-images.githubusercontent.com/44593430/208243855-7dce383f-f81e-4544-99f9-d71bce635fdf.png)

**Comment by probonopd** [comment]
Yes, that would be one way to do it.

**Comment by louies0623** [comment]
It's been a year and it should have been resolved.

**Comment by probonopd** [comment]
I am not working on this currently. Anyone is welcome to work on this.

**Comment by probonopd** [comment]
Closed this. We are using the key next to the spacebar as the command key. On most PC keyboards, "Alt" is printed on that key.
