### ISSUE TITLE
Implement Battery Status icon for laptops

### ISSUE THREAD

**Issue by SanPollo** [helloSystem/hello#323]
Please implement an icon in the top-right of the screen that shows the remaining battery charge in laptops, or that the battery is currently being charged.

The current charge percentage can be found in the hw.acpi.battery.life sysctl value, and the hw.acpi.battery.state value shows 1 for on battery or -1 for charging. In addition, hw.acpi.battery.time shows the estimated remaining time in minutes (if relevant).

**Comment by SanPollo** [comment]
My apologies - I didn't realise that this already existed in the Under Construction section. Please ignore!

**Comment by probonopd** [comment]
Is it working for you? It needs more testing on various machines (including ones that do not have a battery). If it is known to work well, it can graduate out of the "Under Construction" folder :-)

**Comment by SanPollo** [comment]
It seemed absolutely fine for me. Quick question - is there any way for me to disable the under construction warning for these tools? I would like to run the battery and wifi apps on startup so I can properly test them while I am doing other things.

**Comment by probonopd** [comment]
Right-click in Filer, Show Contents, comment it out. It's "just" Python, after all :)
