### ISSUE TITLE
Set hostname in /etc/rc.conf for installed helloSystem

### ISSUE THREAD

**Issue by SanPollo** [helloSystem/hello#325]
As discussed in [this issue](https://github.com/helloSystem/Utilities/issues/119#issuecomment-1015863273), for the installed version of helloSystem, please set the hostname via the _hostname_ option in _/etc/rc.conf_ in order to bring it into line with a standard FreeBSD installation.

More information: [hostname(1)](https://www.freebsd.org/cgi/man.cgi?hostname)

**Comment by probonopd** [comment]
I suspect that currently we are setting it in `/etc/rc.conf.local`. Is this any less correct?

**Comment by SanPollo** [comment]
Personally I set everything in _/etc/rc.conf_, but there's no reason not to set it in _/etc/rc.conf.local_ according to the [man page](https://www.freebsd.org/cgi/man.cgi?query=rc.conf&apropos=0&sektion=5&manpath=FreeBSD+13.0-RELEASE&arch=default&format=html) (although it does mention it exists for "historical reasons").

Anything in _rc.conf.local_ will override whatever is in _rc.conf_. However, if you decide to keep it in _rc.conf.local_, please would you remove the _hostname="FreeBSD"_ line from _/etc/rc.conf_ as it is confusing (and is being overridden anyway)?

**Comment by mr-grooms** [comment]
@probonopd is the best way to resolve this issue by comment out "hostname="FreeBSD"" in https://github.com/helloSystem/ISO/blob/experimental/settings/rc.conf.common

**Comment by probonopd** [comment]
We can remove it from
https://github.com/helloSystem/ISO/blob/experimental/settings/rc.conf.common#L2
and see what happens...
