### ISSUE TITLE
Let HelloOS rolling update

### ISSUE THREAD

**Issue by louies0623** [helloSystem/hello#351]
If you can make HelloOS rolling update, there are two kinds of them, 1. There is a Dev channel to test the alpha or beta update build, which is the main update after the development is completed, 2. The stable version is used to update the system; this is like Arch Linux Same.
This way you don't have to keep re-downloading the ISO, re-copying to CD or reinstalling etc.

**Comment by probonopd** [comment]
Booting the Live ISOs using Ventoy is the cleanest solution for trying out different versions at the moment.

I'd like to expand upon that kind of a system where you can have multiple OS versions, each of which is one single read-only file. This makes the system very robust and easy to have as many versions as you like.

**Comment by probonopd** [comment]
Currently we don't have the capacity to develop anything else than the continuous ISOs that can be booted with Ventoy.
