### ISSUE TITLE
CapsLock to switch keyboard layouts 

### ISSUE THREAD

**Issue by y4rr** [helloSystem/hello#367]
Regarding the proposal about CapsLock on this page - https://github.com/helloSystem/hello/wiki/Welcome-and-unwelcome-technologies

CapsLock should be automatically set to switch keyboard layout, if there's more than one layout is configured on the system. 

Also, it may be tempting to remap this key to some other key, for example ESC or CTRL, but it should not be default if multiple keyboard layouts are used, because being able to easily switch between them is way more important than having easier access to ESC or CTRL.

**Comment by Zoombini50** [comment]
> the letters printed on the keyboard should always match how the software interprets them
I'd argue in favor in favor of software keyboard layouts that can be changed as the user desires, just not with easily-bumped key combinations to switch them! My preferred keyboard is Dvorak, and acquiring a Dvorak hardware keyboard for every computer I use would be 1) expensive, 2) mildly annoying, 3) downright impossible for my laptop unless I pop the keys off and rearrange them myself (and how would the underlying circuitry know I'd done it?). I also need to switch back to QWERTY on occasion (to appease certain games' keyboard controls, whenever someone else needs to use my computer for a minute), but I prefer to do that via a menu or a control panel.

All that aside, I actually came in here to say "Nooooooo!" to a caps lock keyboard switcher. I've tapped Caps Lock when I meant to tap the letter A on so many occasions that I think it would be far worse than Ctrl-space or whatever most systems default to (and that I always end up disabling)! XD

**Comment by probonopd** [comment]
> CapsLock should be automatically set to switch keyboard layout

Strongly against this, as I would type it accidentally all the time.
Even on Windows and on the Mac there seem to be some key combinations that I inadvertently press and then get another keyboard language than what is printed on the actual hardware keys. So annoying!

**Comment by louies0623** [comment]
I have to say that I disagree with your objection, because users in non-Latin languages such as: CJK users, Middle Eastern users, Southeast Asian and Indian users, they need an easy and fast way to switch to English, and the current method is very bad.

**Comment by probonopd** [comment]
I see. So someone woud probably need to write a little utility, like the one we have for volume, to to into the Menu and that would allow for fast keyboard layout switching.

However, it should not be enabled by default, and especially there should be no keyboard shortcut that one can hit accidentally.

**Comment by louies0623** [comment]
I think it should be by language, if it is a Latin language default, it will be locked, and if it is other defaults, it will be enabled.

**Comment by probonopd** [comment]
Maybe yes. Do you know how to find out if a language is a Latin language?
