### ISSUE TITLE
No mouse when install

### ISSUE THREAD

**Issue by NorbertXYZ** [helloSystem/hello#373]
When installing helloSystem in FreeBSD 13.1 under bhyve I have after starting with the iso hello-0.8.0_0H78-FreeBSD-13.1-amd64.iso no mouse available - better to  say: no mouse movement.

my bhyve looks like:

bhyve -c 2 -m 8G -H -w \
  -s 0,hostbridge \
  -s 3,ahci-cd,iso \
  -s 4,ahci-hd,image \
  -s 5,virtio-net,tap0 \
  -s 29,fbuf,tcp=0.0.0.0:5900,wait,w=1280,h=1024 \
  -s 30,xhci,tablet \
  -s 31,lpc \
  -l com1,stdio \
  -l bootrom,/usr/local/share/uefi-firmware/BHYVE_UEFI.fd \
  hello

where iso is a symbolic link to the previous mentioned iso file...  Sorry, I have no other info for help - but hope it helps :-)

Cheers, Norbert

**Comment by probonopd** [comment]
hello, which model of mouse are you using? Can you attach another USB mouse just for testing?

**Comment by probonopd** [comment]
> bhyve

Please try to run the Live ISO on real hardware. I can't debug hypervisors and virtual machines.

**Comment by NorbertXYZ** [comment]
Thanks for the fast reply - but sorry, I have no "bare metal" which I can use...  By the way, the mouse is working (since years) - it is an USB mouse.  And other software works even with a GUI in bhyve...  All the best, Norbert

**Comment by NorbertXYZ** [comment]
Maybe I can find time tomorrow.  But as I said, to test I am using a virtual machine and no real hardware...  I was just interested, how helloSystem looks like...  Other system even like centos are running fine in bhyve - even graphical...  But my focus is *BSD, and if I test other systems I prefare to test it in a virtual environment.  So, maybe we close this issue, and I will see in the next weeks / months how it proceed.  All the best, Norbert :-)

**Comment by probonopd** [comment]
Is bhyve passing through the USB mouse to the host operating system, or is it emulating some other sort of mouse (e.g., PS/2)?

**Comment by NorbertXYZ** [comment]
I don't know...

**Comment by NorbertXYZ** [comment]
oh, wenn I remove the line in the bhyve:
-s 30,xhci,tablet 
then it worked...  It seems to use the "old" usb mouse now :-)

**Comment by probonopd** [comment]
See. This is why I can't support hypervisors/virtual machines, there are just too many things I can't control ;-)

But glad it is working for you now. Have fun exploring helloSystem!
