### ISSUE TITLE
Feature request: Arabic

### ISSUE THREAD

**Issue by madjid27** [helloSystem/hello#374]
This is my first time writing issue.
With that being said; the system still needs lots of missing things that i don't think will interfere with it's philosophy, but there is an urgent one for me that i would like added as soon as possible; which is adding support for the language Arabic and it's keyboard layout.
Thank you for you hard work.

**Comment by probonopd** [comment]
Thanks @madjid27. Dependent on https://github.com/helloSystem/hello/issues/36.

**Comment by probonopd** [comment]
Consider to reopen once we have resources to do this.

**Comment by probonopd** [comment]
Currently we have no one who has the skills to do this.

If anyone who
* Knows Arabic
* Knows how to configure it on FreeBSD
* Can test it
wants to do the work, then please let us know and we can reopen this.

**Comment by madjid27** [comment]
> Currently we are focusing on left-to-right languages, and we have no one in the team who has the skills and time to do think about or implement right-to-left languages.

Okay. Thank you.
