### ISSUE TITLE
about man pages

### ISSUE THREAD

**Issue by 9gay** [helloSystem/hello#375]
there are many ways to display man pages, the ugliest one is https://www.freshports.org/x11/xman/

you can convert man pages to different formats, let's say pdf: `MANPAGER=qpdfview man -T pdf xargs` (had to rely on https://man.openbsd.org/man to figure that out)

basically what's missing is offline GUI browser without web shit, plus unfortunately that conversion above doesn't create clickable links

btw, can you please provide a tool to restore what you removed from base system?

with proper design developer comfort doesn't compromise non-developer comfort and makes it easier for non-developers to become developers if they want to

**Comment by probonopd** [comment]
> with proper design developer comfort doesn't compromise non-developer comfort and makes it easier for non-developers to become developers if they want to

Exactly. This is why we have a Developer image that developers (and in general people who are using the command line) can install on their system.

**Comment by 9gay** [comment]
sorry for misunderstanding, I was confused by .img because in typical bsd .img means image bootable only on usb while .iso means image bootable only on cd/dvd (I have no idea why don't they mix that into single .iso)

**Comment by probonopd** [comment]
In helloSystem, `.iso` means bootable Live system, while `.img` means disk image.
