### ISSUE TITLE
Support for unsupported wireless network cards for roadmap in post v1.0?

### ISSUE THREAD

**Issue by Anvith00** [helloSystem/hello#386]
The OS works quite nice on a lot of devices (have tried in a couple of x86_64 devices) but there seems to be less to no support for wireless cards from Realtek, Broadcom, and Mediatek (which I guess is in the nature of it being a FreeBSD fork).

I believe support for wireless devices would be a nice touch in versions following the v1.0 release.

**Comment by Anvith00** [comment]
(Am no OS or driver expert, but would it be possible to solve FreeBSD's minimal device driver support by making use of linuxkpi 🤔?)

**Comment by probonopd** [comment]
Glad helloSystem is working on many of your machines.

> it being a FreeBSD fork

Not really a fork, it's using the original FreeBSD kernel and drivers without any changes:
https://wiki.freebsd.org/WiFi

Specifically:
* Realtek: https://www.freebsd.org/cgi/man.cgi?query=rtwn&sektion=4&format=html
* Broadcom: https://www.freebsd.org/cgi/man.cgi?bwn(4) and https://www.freebsd.org/cgi/man.cgi?query=bwi&sektion=4&format=html
* Intel: https://wiki.freebsd.org/WiFi/Iwlwifi. FreeBSD is currently working on improving support
* Mediatek: Not supported as far as I know (but I might be wrong). Which devices are you thinking of?

Here is a list of well-supported WLAN adapters for FreeBSD:
https://gist.github.com/grahamperrin/0d6cca0e463c5fdc089e84ed442e214c
If any of the adapters on that list doesn't work out of the box on helloSystem, please let us know.

We want to support all wireless adapters in helloSystem that are supported in FreeBSD.
If an adapter is not supported in FreeBSD, then please ask the FreeBSD developers to support it as helloSystem does not work on drivers.

Thanks!
