### ISSUE TITLE
Idea: Use Inter font as system font

### ISSUE THREAD

**Issue by shilch** [helloSystem/hello#39]
The [Inter font family](https://rsms.me/inter/) is licensed under the SIL Open Font License but looks very similar to the macOS system font (San Francisco) as can be seen [here](https://www.reddit.com/r/typography/comments/g0ppv2/can_you_spot_which_is_sf_pro_and_which_is_inter_v/):

![image](https://user-images.githubusercontent.com/11890358/99309396-a4fa4e80-2859-11eb-8cb8-998f7f9deb7b.png)

**Comment by probonopd** [comment]
Thanks for pointing me to the Inter font family. Indeed I am aware of it.

The goal here is to create something tasteful that is _welcoming to switchers from the Mac_, not something that necessarily looks very much like recent versions of macOS.

Currently the URW Nimbus familiy is used as the UI font, which is a high-quality digital version of the traditional [Helvetica](http://www.documentarymania.com/player.php?title=Helvetica) font, albeit under a different name.

**Comment by shilch** [comment]
> Are there specific reasons you would prefer Inter to URW Nimbus Sans?

I wasn't sure how close you want the system to look like macOS. Personally, I would prefer a look close to Mojave or the pre-Yosemite releases (not sure which font they used there).

**Comment by probonopd** [comment]
For a 10.0-10.9ish look, one could also consider using the Bigelow & Holmes TTF fonts in FreeBSD, which are made by the same designer and quite resemble the Lucida Grande UI fonts in Mac OS X.
