### ISSUE TITLE
Lean(er) Qt?

### ISSUE THREAD

**Issue by narinishi** [helloSystem/hello#401]
Qt5 is a rather large framework, have you looked into reducing the size?

https://www.qt.io/blog/2017/05/31/qt-lite-qt-5-9-lts
A blog post showing size reductions from using functionality introduced with Qt 5.8.

https://github.com/rochus-keller/LeanQt
A fork of Qt 5.6.3, GUI-oriented and thus missing some other features.

**Comment by probonopd** [comment]
Hi @narinish. While I am all for getting this as lean as possible, I am not in for the kind of work and trouble this would likely involved. Especially since `pkg install <any Qt app>` would then pull in _yet another_ Qt.
