### ISSUE TITLE
Improve Choose a language

### ISSUE THREAD

**Issue by louies0623** [helloSystem/hello#416]
![VirtualBox_PC-2_04_12_2022_17_28_22](https://user-images.githubusercontent.com/44593430/205489070-cf0fbad4-9f61-4ec9-a684-d814f9b05eab.png)
This menu does not have a blue selection box and allows the user to click to confirm the selected item and confirm the next step, as photo.
![Diagnostico-de-hardware-en-mac-c](https://user-images.githubusercontent.com/44593430/205489112-4b21cff4-fd5c-4c0c-b0d4-2bd3d7c1b110.jpeg)

**Comment by probonopd** [comment]
Our version does not need the extra button click, so I think our version is better :+1:

**Comment by louies0623** [comment]
Then, I want it to have a selection color box like a menu, as shown in the picture.
![Global-Menu](https://user-images.githubusercontent.com/44593430/206707052-3c132196-f2b1-4204-a909-838aff6dcd32.jpg)

**Comment by probonopd** [comment]
Since the window goes away immediately as soon as you click on a language, you just don't see the selection color.

**Comment by louies0623** [comment]
So how do I make sure I'm choosing the right language, the list is long.

**Comment by louies0623** [comment]
Muscular Dystrophy
[image](https://user-images.githubusercontent.com/44593430/208215648-32610723-c7ff-4505-aa35-5b801c91981d.png)

**Comment by louies0623** [comment]
And when I was translating, I was bored to see the translation progress of other languages. Hebrew has been fully translated but it is not in the list.

**Comment by probonopd** [comment]
Well, the list shows the languages that are currently offiially supported in helloSystem. Possibly the list may be expanded in the future, but for now those are the ones we are focusing on.

**Comment by louies0623** [comment]
When the computer's usb port is full, when the touchpad is broken, I can't access it with the keyboard.

**Comment by louies0623** [comment]
@probonopd There is a description message below the latest language options, and some of our users need to click on their language to understand what is being said.
