### ISSUE TITLE
Add screensaver

### ISSUE THREAD

**Issue by louies0623** [helloSystem/hello#417]
Sometimes I wish I could display the current time when the computer is idle, or be elegant when it is in standby.

### [Gluqlo](https://github.com/alexanderk23/gluqlo) Based on XScreensaver
![image](https://user-images.githubusercontent.com/44593430/205491608-ad21ecf1-aab9-4048-942f-e92a31942323.png)

### XScreensaver Flurry
but it's quite intensive on the computer and not a very energy-efficient method of not using your computer.
![image](https://user-images.githubusercontent.com/44593430/205496193-9a91978e-c713-40c1-8682-34aba4bdfe7b.png)

### [[flux](https://github.com/sandydoo/flux)] MIT license 
[Linux](https://github.com/sandydoo/flux-screensavers/issues/1)
![image](https://user-images.githubusercontent.com/44593430/205490745-9b930732-4e5a-428b-bc84-dbe6a2049180.png)

**Comment by probonopd** [comment]
Are screensavers still being used nowadays? I think it's more eco-friendly to have the display powered down if not in use, as it done generally.

**Comment by probonopd** [comment]
![image](https://user-images.githubusercontent.com/2480569/206105675-3cbfce14-cbe5-45d4-8670-e77c9e24cc0d.png)
