### ISSUE TITLE
Add Crash screen

### ISSUE THREAD

**Issue by louies0623** [helloSystem/hello#418]
As shown

![image](https://user-images.githubusercontent.com/44593430/205506752-64da6849-dc85-44bf-b920-be7cd4898a9e.png)

![image](https://user-images.githubusercontent.com/44593430/205506910-871e68bf-ec8c-413f-98a5-1adc51f0a4ba.png)
It needs to clearly show what went wrong, like windows BSOD
QR code is used to lead to error feedback.
![image](https://user-images.githubusercontent.com/44593430/205507078-094bb4dc-2c61-427e-b427-acda1587885d.png)

**Comment by probonopd** [comment]
Not sure whether this is possible in FreeBSD. It would need to be still somewhat "alive" in order to do that...

**Comment by louies0623** [comment]
i try to design it.

**Comment by louies0623** [comment]
Minimum recommended screen (640X480)
![think_工作區域 4](https://user-images.githubusercontent.com/44593430/205593857-2dc5c4a8-eef8-4f10-8178-ae3c4580d12c.png)
![think_工作區域 2](https://user-images.githubusercontent.com/44593430/205593868-fa1fe0c6-e667-4c52-ac7a-43069973d7e4.png)

**Comment by louies0623** [comment]
DEMO
![thinkB_工作區域 5](https://user-images.githubusercontent.com/44593430/205600969-140563ff-b289-4e7d-82b1-4c757635a192.png)

**Comment by probonopd** [comment]
The question is: Can FreeBSD do it? How?
"Normal" programs can't write anything to the screen after a crash.
So the kernel would need to do it somehow?

**Comment by louies0623** [comment]
Also, it might take help from someone who has done the research.

**Comment by louies0623** [comment]
https://www.freebsd.org/cgi/man.cgi?query=bsod&apropos=0
I'm not sure if this.

**Comment by probonopd** [comment]
Please try it out. Please always try everyhting out first before you suggest it. I do not have the time to test random things. I can only consider suggestions that have been tested and are known working. Thanks.
