### ISSUE TITLE
Qt anti-virus software in helloSystem 

### ISSUE THREAD

**Issue by louies0623** [helloSystem/hello#423]
In order to protect users, should the system have a built-in anti-virus software, such as Clam One (qt) or use Clam AV to rewrite an interface as a built-in anti-virus software.

https://github.com/ClamOne/ClamOne

**Comment by probonopd** [comment]
At this point, you can install AV from FreeBSD Ports.
It is not planned to ship AV software with helloSystem.

**Comment by louies0623** [comment]
It would be nice to add it in the sideload menu, because that's how users can easily install.

**Comment by louies0623** [comment]
@probonopd Please think about it, if there is something like this, it is also very dangerous on Unix, because the system is not virus-free, and data needs to be protected, which must be a must.

![image](https://user-images.githubusercontent.com/44593430/209497886-1cd304b3-100d-4dfa-8d93-9d9ec8155118.png)

**Comment by probonopd** [comment]
I was assuming this was a pure Windows problem, but apparently it is now also an Ubuntu problem...

**Comment by louies0623** [comment]
It is best if the default is already installed on the system, you can also read this news.
https://arstechnica.com/information-technology/2022/09/never-before-seen-malware-has-infected-hundreds-of-linux-and-windows-devices/

**Comment by louies0623** [comment]
Need UI interface
