### ISSUE TITLE
Foreign language input method

### ISSUE THREAD

**Issue by louies0623** [helloSystem/hello#425]
![image](https://user-images.githubusercontent.com/44593430/206800906-2f4397be-ecec-42dd-ae34-bfd1edd1fe8d.png)
Need a foreign language input method, I prefer ibus, it is very stable and has a good interface.  I don't like Fcitx because the default icon and theme are ugly, so I think if want to use it, it have to use the Papirus icon
https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/issues/1271

**Comment by probonopd** [comment]
Do you know how to install ibus qith a Qt user interface?

**Comment by probonopd** [comment]
Both IBus and Fcitx provide a way for users to easily switch between different input methods while they are typing.

The main difference between the two frameworks is that IBus is developed by GNOME, while Fcitx is developed by the Fcitx project.

Given its heritage, IBus will never become part of helloSystem.

You can install a Qt IBus frontend:

```
% pkg search fcitx | grep qt
fcitx-qt5-1.2.7                Fcitx support for Qt5
fcitx5-qt-5.0.8                Fcitx support for Qt5
```

I don't know how to set up or use these, but I hope this information helps.

**Comment by louies0623** [comment]
I have nothing against using fcitx just wish it had a theme to watch.

**Comment by probonopd** [comment]
Can you post a screenshot of what you don't like or think needs to be changed?

**Comment by louies0623** [comment]
Besides, this software does not support many languages, if possible, use Slim.
![image](https://user-images.githubusercontent.com/44593430/206843386-b1ce3893-ca7e-44bd-8260-a61dc379bf83.png)
![image](https://user-images.githubusercontent.com/44593430/206843564-63f3690f-93e4-4362-ab1e-2edba402c2e5.png)

**Comment by probonopd** [comment]
I mean, how does this look on helloSystem when you install one of the packages I had mentioned? Is there any pre-configuration or design change we should do?

**Comment by probonopd** [comment]
Let's talk about this topic in https://github.com/helloSystem/docs/issues/34.
