### ISSUE TITLE
In non-Nimbus text is perfectly aligned.

### ISSUE THREAD

**Issue by louies0623** [helloSystem/hello#426]
![think](https://user-images.githubusercontent.com/44593430/206809246-7b73a1f6-f8af-4cfd-b438-86a3e22084da.png)
![think](https://user-images.githubusercontent.com/44593430/206807381-736c6819-665a-4985-86fd-df0638d28a00.png)

**Comment by louies0623** [comment]
This is NimbusSans with baseline height corrected.
https://github.com/scriptableorg/NimbusSans

**Comment by probonopd** [comment]
This is not an issue of Nimbus Sans.

The issue is that Nimbus Sans does not contain all special characters, and hence another font is being used to render the special characters.

This combination of two fonts leads to this issue.

We need to find a solution for this.

**Comment by louies0623** [comment]
https://www.fontsquirrel.com/fonts/TeX-Gyre-Heros

![image](https://user-images.githubusercontent.com/44593430/206858056-0d9bf96f-0af9-453d-8b18-0207b784cc49.png)
This one is based on Nimbus Sans, which was in turn based on Helvetica.

**Comment by probonopd** [comment]
Well, Nimbus Sans is Helvetica under another name. Hot Helvetica Neue. That is a later remake of it.

**Comment by louies0623** [comment]
Otherwise, teach me how to change the font of the menu and let me try to see how other fonts display.

**Comment by louies0623** [comment]
![image](https://user-images.githubusercontent.com/44593430/206865109-2bd0c804-ae79-420e-8179-275bf417a861.png)
I can't find a font that is more in line with helvetica and apple symbol than inter, followed by Noto sans

or maby GNU Unifont

**Comment by probonopd** [comment]
As explained already may times, we are using Nimbus Sans. We do not plan to use anything else than Nimbus Sans. Nimbus Sans is closest to the "real" Helvetica as possible. This is as close to ideal as possible.

**Comment by louies0623** [comment]
Then use the corrected.

**Comment by louies0623** [comment]
![image](https://user-images.githubusercontent.com/44593430/209014053-70854595-847f-4189-bc16-b4684b8337a0.png)

**Comment by louies0623** [comment]
You can refer this .
![image](https://user-images.githubusercontent.com/44593430/209893715-5cb9cb44-b7e6-47c9-a364-c97256202c63.png)
![image](https://user-images.githubusercontent.com/44593430/209893734-9a82535b-ac87-492d-83d1-ef9ad7a9ce11.png)

**Comment by louies0623** [comment]
Chivo font
https://github.com/Omnibus-Type/Chivo
