### ISSUE TITLE
Use maliit as an on-screen keyboard

### ISSUE THREAD

**Issue by louies0623** [helloSystem/hello#427]
This is a good helper when some character users can't type, especially emoji.

**Comment by probonopd** [comment]
For now, iit can be installed by the user wih `sudo pkg install deskutils/maliit-keyboard`.

https://www.freshports.org/deskutils/maliit-keyboard/

**Comment by louies0623** [comment]
Sometimes the system doesn't support my keyboard so I need.

**Comment by probonopd** [comment]
This is not a typical desktop system. This is not what helloSystem is made for.

We are are aiming at mouse operated devices. Not touch.

**Comment by louies0623** [comment]
@probonopd I once encountered a situation where I was rushing to type a report with a laptop outside. Halfway through the typing, some keys on the keyboard could not be pressed. I couldn’t borrow an external keyboard, so I could only use the on-screen keyboard and mouse to write a word. Type one slowly, the key report is still in Chinese, I can’t use the character map to search word by word slowly, it’s very torturous.

**Comment by louies0623** [comment]
if you forget this will help you.
![image](https://user-images.githubusercontent.com/44593430/209469061-d57658fb-ab86-49fc-8e3d-b7eb9864ef02.png)

**Comment by louies0623** [comment]
There is also an ATM, so should it be controlled with a mouse or a keyboard?
![image](https://user-images.githubusercontent.com/44593430/209492510-1738c104-aa83-4f13-b3a9-1d61ee285435.png)

**Comment by louies0623** [comment]
@probonopd 
System 7.0 Is have
![image](https://user-images.githubusercontent.com/44593430/209682851-ecbdd9af-f46a-4bc6-b36e-5e6bd3e32541.png)

**Comment by louies0623** [comment]
Mac OS 8

https://user-images.githubusercontent.com/44593430/209910108-40906a18-d730-4238-a198-55cf4947c319.mp4
