### ISSUE TITLE
Use "scim" as a foreign language input method.

### ISSUE THREAD

**Issue by louies0623** [helloSystem/hello#428]
https://github.com/scim-im/scim
![image](https://user-images.githubusercontent.com/44593430/206836093-7f059510-d600-41ca-9ade-2c020b33fe85.png)

**Comment by louies0623** [comment]
![image](https://user-images.githubusercontent.com/44593430/206839376-b4c22023-b83e-4169-868c-6a3770cc2e9e.png)
If you switch here, it is troublesome and redundant. You can switch in the upper right corner, but you have to open the window to set the switch, which is unnecessary.

**Comment by probonopd** [comment]
Let's talk about this topic in https://github.com/helloSystem/docs/issues/34.
