### ISSUE TITLE
Add lock screen

### ISSUE THREAD

**Issue by louies0623** [helloSystem/hello#429]
Temporary diarrhea or urinary urgency at work, and not in front of the computer, Provide users with privacy protection.

**Comment by probonopd** [comment]
Duplicate of https://github.com/helloSystem/hello/issues/170.

Not part of https://dl.acm.org/doi/book/10.5555/573097.

**Comment by probonopd** [comment]
Our system is intended to become as simple as the Mac in the 80s, and to remove all the complicated stuff.

**Comment by louies0623** [comment]
Yeah...It's as easy as letting others steal information.

**Comment by probonopd** [comment]
Yes. The Mac never had the concept of "accounts" well until late in System 7.

**Comment by louies0623** [comment]
https://github.com/helloSystem/ISO/issues/339

**Comment by louies0623** [comment]
If your mobile phone has a password lock or graphic lock or face lock, it is still not necessary for laptop users.
