### ISSUE TITLE
Display protocol? X11, Wayland or a new thing?

### ISSUE THREAD

**Issue by sandov** [helloSystem/hello#43]
I'm interested in what display protocol you plan to use for Hello. Just keep using X11, port Wayland, or write something from scratch? What about screen tearing?

I really hope this project succeeds and I wholeheartedly agree with your opinions about usability and the current state of the Unix desktop.

**Comment by sandov** [comment]
Nevermind. I hadn't read the article in the wiki that talks about it. 

My bad.

**Comment by probonopd** [comment]
You may be interested in https://gist.github.com/probonopd/9feb7c20257af5dd915e3a9f2d1f2277.
