### ISSUE TITLE
When shutting down or restarting, show which user is using

### ISSUE THREAD

**Issue by louies0623** [helloSystem/hello#430]
When you shut down the computer after using it, you will notice that there are other users who need to use the computer.
![PapjW](https://user-images.githubusercontent.com/44593430/206840750-d9bc5336-bf64-4e21-97ef-950dd9df1777.png)

**Comment by probonopd** [comment]
helloSystem is designed for _personal_ computers, we are assuming that no other users are logged in.

**Comment by louies0623** [comment]
@probonopd  The reality is that when you are at work and you have to lend your computer to family members, and they accidentally shut it down, you have to deal with it.

**Comment by probonopd** [comment]
helloSystem is designed for _personal_ computers, where there is only one user.
For more advanced setups, users can change the `slim` configuration.

**Comment by probonopd** [comment]
Yes. Only for advanced users.

**Comment by louies0623** [comment]
I really hope you have a family account on the computer for the young children, and then report halfway through the call to let the children use the computer, switch to this account, and turn off your computer without paying attention after the children are done playing, I  did as a child.

**Comment by louies0623** [comment]
It's just that the computer I shut down is... the director's computer

**Comment by probonopd** [comment]
When I grew up, computers didn't have "accounts".

**Comment by louies0623** [comment]
Which space-time system does not have account settings.

**Comment by probonopd** [comment]
https://dl.acm.org/doi/book/10.5555/573097 :)

**Comment by louies0623** [comment]
Mac OS 7
![螢幕快照 2022-12-29 下午2 43 43](https://user-images.githubusercontent.com/44593430/209914252-2ebc4c55-e4bc-4872-a0a1-e32982ad9203.png)
