### ISSUE TITLE
Support compressed files

### ISSUE THREAD

**Issue by louies0623** [helloSystem/hello#434]
No files are displayed when the zip file is opened, and there is no software to decompress or compress.

**Comment by probonopd** [comment]
When you double-click a zip file, then it _should_ be mounted and the files _should_ be displayed. If this does not work, then it is a bug.

**Comment by louies0623** [comment]
The zip file I downloaded doesn't show any files.
and how do we compress the file.

**Comment by louies0623** [comment]
[PC-2-screen0.webm](https://user-images.githubusercontent.com/44593430/206888887-c4d2d270-57c7-4aa6-9cc5-70a2aca12ff5.webm)
And what the hell is this option, just put all the functions in one list, it’s unnecessary.

**Comment by probonopd** [comment]
This is so that users can define their own menu items without coding.

**Comment by louies0623** [comment]
open this issue as this is not fixed
**should be like this.**
![VirtualBox_PC-2_11_12_2022_20_10_18](https://user-images.githubusercontent.com/44593430/206902829-6d873044-2a8f-4e09-b003-07fdfa2510cc.png)
**Relly**
![VirtualBox_PC-2_11_12_2022_20_09_47](https://user-images.githubusercontent.com/44593430/206902830-cb8b2d4e-a754-48d0-a93f-7b6480cadb6b.png)

**Comment by probonopd** [comment]
Well, it should be like on my screenshot.

**Comment by louies0623** [comment]
0H246 
@probonopd  You go to download Ubuntu Font and then open the file, the problem will appear.

[PC-2-screen0.webm](https://user-images.githubusercontent.com/44593430/208221281-b5557211-6322-48dd-89c9-424f5385c6de.webm)

**Comment by probonopd** [comment]
Strange. Works nicely on my dev machine.

![image](https://user-images.githubusercontent.com/2480569/208240363-81adb9f9-770a-4743-9ab9-f274fb067274.png)

What happens if you press Command-R to reload the Filer window?

**Comment by louies0623** [comment]
Using Command-R it works fine, but on reboot it comes back blank, weird...

**Comment by probonopd** [comment]
There is still some issue with Filer not always refreshing its windows at the right time. It is not specific to compressed files but is the root cause here.
