### ISSUE TITLE
Requires colorless display functionality in accessibility tools

### ISSUE THREAD

**Issue by louies0623** [helloSystem/hello#443]
Some people will feel tired from the color of the screen, which will affect his work efficiency and need this function.
https://github.com/ugjka/kwin-effect-grayscale

**Comment by probonopd** [comment]
If anyone wants to work on any accessibility aspects, they are free to do so. I am currently not working on any accessibility aspects.

Editing `/usr/local/etc/xdg/stylesheet.qss` should go a long way.
