### ISSUE TITLE
Make Chromium use System Title Bar and Borders

### ISSUE THREAD

**Issue by probonopd** [helloSystem/hello#45]
Click on top of browser window and activate 'Use system Title Bar and Borders' - how to do this as part of the system-wide preconfiguration?

![image](https://user-images.githubusercontent.com/2480569/99847004-a6888700-2b77-11eb-9e95-730f3b8f67c8.png)

**Comment by probonopd** [comment]
Use a `master_preferences` but how exactly?

**Comment by grahamperrin** [comment]
Duplicate of https://github.com/helloSystem/Menu/issues/29 or vice versa? 

Is this still truly a good first issue?

**Comment by grahamperrin** [comment]
### Discovering the preference

1. Launch Chromium without the required appearance
2. in a terminal window
3. `cd ~/.config/chromium/Default` 
4. `cp Preferences ~/Desktop/chromium-titlebar-disabled.json`
5. give Chromium the required appearance then return to the terminal
6. `cp Preferences ~/Desktop/chromium-titlebar-enabled.json`
7. compare the two files.

Whilst simple output from [diff(1)](https://www.freebsd.org/cgi/man.cgi?query=diff(1)) might not help, something with a GUI will. 

```text
% pkg rquery '%o %v %R' meld
textproc/meld 3.20.1,1 FreeBSD
% 
```

![2021-01-03 14:04:10](https://user-images.githubusercontent.com/192271/103480633-44a17b00-4dcd-11eb-88d5-79c59ab43845.png)

### `custom_chrome_frame`

It's a boolean preference in a JSON file that does not have a `.json` suffix. 

`~/.config/chromium/Default/Preferences`

### Hint

After you finish with the `~/Desktop` copies of the file, set one aside for future reference. With the `.json` suffix, it might be usefully viewed in Firefox, or any other application that's capable of presenting a human-friendly view. 

![image](https://user-images.githubusercontent.com/192271/103481014-f80b6f00-4dcf-11eb-839d-b969fd0641f2.png)

**Comment by grahamperrin** [comment]
### Writing the preference before a first run of Chromium

#### Experiment 001

Essentially: 

1. quit Chromium. 
2. `cd ~/.config/` then set aside your usual Chromium configuration directory
3. create a path
4. write the preference alone to the preference file alone.

```text
% mv chromium chromium.setaside
% cd
% mkdir -p /usr/home/grahamperrin/.config/chromium/Default
% echo "{"custom_chrome_frame":true}" > /usr/home/grahamperrin/.config/chromium/Default/Preferences
% chromium
chromium: Command not found.
% chrome
```

![image](https://user-images.githubusercontent.com/192271/103481222-6dc40a80-4dd1-11eb-8fb5-44c72ed299ce.png)

There's the title bar, however the screenshot was preceded by a dialogue about a corrupt profile.

**Comment by grahamperrin** [comment]
https://github.com/helloSystem/hello/issues/45#issuecomment-731366178

> Use a `master_preferences` file but how exactly?

I don't know. 

Strict searches such as this find plenty of discussion, but (at a glance) **nothing about pre-configuration**:

<https://www.google.com/search?q=%22custom_chrome_frame%22+preset%7Cpreconfigure%7Cdefault&tbs=li%3A1#unfucked>

https://www.freebsd.org/cgi/man.cgi?query=hier(7) draws attention to: 

`/usr/share/skel`

<https://www.google.com/search?q=%2B%22%2Fusr%2Fshare%2Fskel%22+%2BChromium+%2BPreferences&tbs=li%3A1#unfucked&tbs=qdr:y> finds nothing. 

If there's a Linux equivalent to `/usr/share/skel` then a Linux-oriented search might find examples of people who truly **do** wish to preconfigure Chromium (or Chrome) …

**Comment by probonopd** [comment]
> If there's a Linux equivalent to /usr/share/skel t

Use the search, Luke!

Ours is at
https://github.com/helloSystem/ISO/tree/experimental/overlays/uzip/hello/files/usr/share/skel

**Comment by grahamperrin** [comment]
I mean, a _Linux_ equivalent (for Google search purposes) … this is open for anyone to be Luke :-)

**Comment by grahamperrin** [comment]
Not effective with `hello-0.3.0_0C155-FreeBSD-12.1-amd64.iso`. 

First run, after installation: 

![image](https://user-images.githubusercontent.com/192271/104082271-aed27980-522c-11eb-87ce-63e7af24d770.png)

**Comment by probonopd** [comment]
Too bad it didn't work so far. If anyone ever finds out how to preconfigure this, please let us know. 

In the meantime we are shipping Falkon which uses the Global Menu out of the box.

**Comment by AndreasTNT** [comment]
Why would we want chromium?

**Comment by probonopd** [comment]
Chrome extensions/plugins like uBlock Origin do not work in Falkon. And the Linux version of Chromium is useful for people who need Widevine DRM.

**Comment by AndreasTNT** [comment]
Couldn't firefox be used? Or am I missing something.

**Comment by probonopd** [comment]
It could, but it is ugly as hell and recently got worse.

**Comment by AndreasTNT** [comment]
I haven't tested this, https://stackoverflow.com/questions/11505767/how-can-i-set-chrome-to-use-system-titlebars-and-border-in-preferences-file

**Comment by grahamperrin** [comment]
> this

`custom_chrome_frame` is above.

**Comment by probonopd** [comment]
Ah right @grahamperrin. I was thinking of the Global Menu. Haven't seen a working solution on FreeBSD for that yet.

**Comment by probonopd** [comment]
This seems to do the trick:

```
{
   "browser":{
      "custom_chrome_frame":false,
      "has_seen_welcome_page":true
   }
}
```

**Comment by probonopd** [comment]
Feel free to comment here in case the issue is not fixed properly.
Thanks for your help @grahamperrin.
