### ISSUE TITLE
Add On-screen keyboard

### ISSUE THREAD

**Issue by louies0623** [helloSystem/hello#458]
![image](https://user-images.githubusercontent.com/44593430/210176647-600a7117-2937-4ced-87ec-e94ec5b3d07c.png)
In addition to helping laptop users in missing keys, it can also detect whether the Mac keyboard function keys correspond correctly in the hello system.

**Comment by probonopd** [comment]
Please don't open duplicates.

**Comment by louies0623** [comment]
@probonopd I strongly disagree with your request to replace the on-screen keyboard with a character set, because it is very simple for Latin-speaking countries, but it is not true for CJK languages. This usage is as troublesome as using a Japanese typewriter.

![image](https://user-images.githubusercontent.com/44593430/210471267-a3ad3b87-445f-495c-b987-eb36d5756b83.png)
