### ISSUE TITLE
Remove the claim about mediaanalysisd

### ISSUE THREAD

**Issue by quackerex** [helloSystem/hello#473]
This claim a has been debunked by concluding.

> There is no evidence that local images on a Mac have identifiers computed and uploaded to Apple’s servers when viewed in Finder windows.

https://eclecticlight.co/2023/01/18/is-apple-checking-images-we-view-in-the-finder/

Therefore, remove this claim on README as it is no longer true.
> Because Apple runs services like mediaanalysisd on macOS which phone home to Apple, doing whatever. Who knows for sure?

**Comment by probonopd** [comment]
Well. It did phone home to Apple without asking the user for permission. It apparently didn't contain payload, but that might change with any new update. "doing whatever" is a pretty accurate description. No one knows for sure. And that is the point. Why should the operating system contact any servers when the user locally works with the machine.

**Comment by probonopd** [comment]
> There are legitimate reason to connect to servers. Important ones such as for rapid security responses, remote lock/wipe in the case of macOS.

I consider these anti-features.

> wildly jump to conclusions

Maybe the article did that; I don't. I don't like when my computer "phones home", even if with zero payload. It still tells the OS vendor (and possibly the NSA) at which time someone used a computer at a given IP address. This kind of behavior is not acceptable for me.
