### ISSUE TITLE
Cmd key?

### ISSUE THREAD

**Issue by coolaj86** [helloSystem/hello#48]
There are two reasons I use MacOS:

1. Cmd and Ctrl are separate keys that behave in a predictable way.
    Cmd+C is ALWAYS copy. Ctrl+C is ALWAYS cancel.
2. Trackpad w/ Acceleration that *feels* good
    (this is actually my number 1, but that's besides the point)

This is why I just can't get back into Linux or Windows, despite trying (well, and many other reasons on Windows, but if I could get those two things, I could *maybe* use it productively).

I would assume that getting Cmd to function properly on any other OS is just... NEVER going to happen. Am I wrong? Will _hello_ be a shining beacon of light in this arena?

**Comment by probonopd** [comment]
Yes, it's on the roadmap: https://github.com/helloSystem/hello/issues/46
