### ISSUE TITLE
Cannot boot 0.8.1 on MacBookPro11,1

### ISSUE THREAD

**Issue by raylapnt** [helloSystem/hello#487]
Attempting to install on a 2013 macbook pro.  Installer crashes shortly after the freebsd splash screen appears.  This causes the macbook to reboot.

**Comment by probonopd** [comment]
Please boot 0.8.1 in verbose mode by pressing v as soon as the screen becomes all grey. Watch for error messages.

**Comment by probonopd** [comment]
Also, which exact model? E.g., `MacBookPro1,1`

**Comment by raylapnt** [comment]
It is a MacBookPro11,1  I tried to look for error messages in verbose mode..  it scrolls way too fast for me to see error messages before it reboots

**Comment by probonopd** [comment]
Need to video it.

**Comment by probonopd** [comment]
Just guessing here, you might be running into https://github.com/helloSystem/ISO/issues/455.

As a workaround, try

```
unset geom_ventoy_load
boot
```
at the bootloader prompt.

To get to the bootloader prompt, press backspace as soon as the screen becomes all grey, then press esc.

**Comment by raylapnt** [comment]
I tried video in slow motion.. here is a screen cap right before it reboots


![2023-03-11_12-42](https://user-images.githubusercontent.com/127614615/224503603-615afb88-a5aa-4982-8ba8-d22b641409ce.png)

**Comment by raylapnt** [comment]
I am getting "no such file or directory" after using the command provided

**Comment by probonopd** [comment]
Looking at your screenshot, it seems very likely that this is https://github.com/helloSystem/ISO/issues/455. Hence closing here as a duplicate.

**Comment by raylapnt** [comment]
The workaround does not seem to work

Am i not doing it right?

![20230311_130430](https://user-images.githubusercontent.com/127614615/224504752-070ff64d-59eb-4d8e-9e8c-9b8526f5a5a6.jpg)

**Comment by probonopd** [comment]
My bad, that workaorund doesn't work. We need to find a way to tell the bootloader not to load the ventoy kernel module on affected machines.

**Comment by louies0623** [comment]
You can try the latest development preview as it has been recently resolved.
https://github.com/helloSystem/ISO/issues/335
