### ISSUE TITLE
Ability to cancel the system installation

### ISSUE THREAD

**Issue by 4knm2ps3n52lpnkw** [helloSystem/hello#491]
When the system installation has started, there is no button to cancel it, even if you press Ctrl+C in the log shell

(Tested on 0.8.2_0H331)

**Comment by probonopd** [comment]
When the system installation has started, there is _intentionally_ no button to cancel. For the same reason, there are no window controls. Interrupting an installation after it has started would result in an unbootable system, and hence we don't allow to interrupt the installation while it is running.
