### ISSUE TITLE
Ability to choose a modern UI

### ISSUE THREAD

**Issue by 4knm2ps3n52lpnkw** [helloSystem/hello#494]
Allow users to choose a modern flat UI, like one of Catalina (or even Ventura if you like)

Should be available during (or right after) the installation and any time from the settings

**Comment by probonopd** [comment]
Hello @4knm2ps3n52lpnkw. Thanks for sharing your suggestion. However, a "modern flat UI" is not part of the [human interface guidelines](https://dl.acm.org/doi/book/10.5555/573097) we are intending to loosely follow. In fact, I think  "modern flat UI" is what made today's macOS un-Mac-like.

**Comment by probonopd** [comment]
Well, "best" is obviously very subjective, but yes, for someone who grew up in the world described by that book, it's an ideal to strive for. At least directionally, when it comes to the general ideas.
