### ISSUE TITLE
Dark mode for UI

### ISSUE THREAD

**Issue by 4knm2ps3n52lpnkw** [helloSystem/hello#495]
Somewhat related to #494

**Comment by probonopd** [comment]
Hello @4knm2ps3n52lpnkw. Thanks for sharing your suggestion. However, dark mode is not part of the [human interface guidelines](https://dl.acm.org/doi/book/10.5555/573097) we are intending to loosely follow. We are going for WYSIWYG: What you see is what you get. Black text on white background. This was a major breakthrough in the Macintosh, after the amber and green on black computer displays before it.
