### ISSUE TITLE
Cannot Set Date and Time

### ISSUE THREAD

**Issue by bert003** [helloSystem/hello#499]
This is my first time using helloSystem. Please bare with me. I found the following issues:

1. When trying to set the date, I get a message that Date and Time is not installed.

2. When I install Chrome, it says it is installed but does not appear in the menu. Also the disk named chrome remains mounted and I cannot eject it.

How do you install additional software please?

**Comment by probonopd** [comment]
Select "Chromium" from the System menu, it will ask you whether you want to download it.

**Comment by bert003** [comment]
Thanks.

And what about the "Date and Time not installed" message please? Is there something else which I need to install?

**Comment by probonopd** [comment]
Where do you see this message? Probably it is not implemented yet.

**Comment by bert003** [comment]
I click the time on the top right (ex: 10:05 AM). It then displays the whole date: ex: Saturday, April 15, 2023 10:05:20 AM UTC. Then I click the whole date and it gives me this message as a pop-up:

_The application 'Date and Time' can't be launched because it can't be found._

**Comment by probonopd** [comment]
Yes, that application is not yet written.

**Comment by bert003** [comment]
Noted. Thanks

**Comment by probonopd** [comment]
Started making it:

![image](https://user-images.githubusercontent.com/2480569/232208476-f328affa-676c-46ba-b7e2-67cec604182c.png)

Any volunteers want to work on it?

https://github.com/helloSystem/Utilities/tree/master/Preferences/Date%20and%20Time.app

**Comment by bert003** [comment]
Wow! Looks really nice. Appreciate your prompt support on this.

I am interested in working on it but I would need to learn how to program in Qt using Python in order to be able to help. I know Python already. Any templates for the helloSystem as a starting point please?

**Comment by probonopd** [comment]
Check out https://hellosystem.github.io/docs/developer/applications.html
and the source code of the existing utilities at [https://github.com/helloSystem/Utilities/](https://github.com/helloSystem/Utilities/t)

**Comment by bert003** [comment]
Noted and visited the links provided. Please let me know where I can start from.

**Comment by probonopd** [comment]
Hi @bert003, I am not sure what exactly you are looking for, but I left some TODOs in the code:

https://github.com/helloSystem/Utilities/blob/94eebc9d79ab097af61b442b92bd2a739007fc20/Preferences/Date%20and%20Time.app/Date%20and%20Time#L3-L5

In general, when you search for "TODO" and "FIXME" you'll find areas that could benefit greatly from contributions.

**Comment by bert003** [comment]
Noted. Yes I just wanted to know in which applications is help needed. Ok let me have a look at the Date and Time Application.

Shall I create a personal fork of the project on my GitHub account? Or do you suggest another way? What about testing?

Sorry for asking a lot but would really like to contribute in the best possible way. Thanks for your time.

**Comment by probonopd** [comment]
> Ok let me have a look at the Date and Time Application.

Great!

> Shall I create a personal fork of the project on my GitHub account?

Yes. And once you are satisfied with your changes, ping me so that I can test it.

Thanks. :+1:

**Comment by bert003** [comment]
Hi, excuse my late reply but had a tough week and could not work on this. I have forked the repository. When I do the changes, shall I commit directly to the master branch or create a new branch for the commit?

**Comment by probonopd** [comment]
Hi @bert003, best make a separate branch with your changes, then ping me once you are happy with them. Thanks!

**Comment by bert003** [comment]
Is there a way that I can test myself though before committing? Can I contact you separately in order not to spam this thread?

**Comment by probonopd** [comment]
Just make your changes in the code, then run the app by double-clicking it as usual.

**Comment by bert003** [comment]
The spinner is appearing on the bottom left as shown below. Is that its intended position?

![date-time-spinner](https://user-images.githubusercontent.com/20399702/235283522-7174adc1-39b0-458a-ad54-9df761ff53ed.JPG)

**Comment by probonopd** [comment]
Well... not really. I hadn't thought about finding a position because I couldn't get it to work properly anyway. 
At least we should make room for it, and the spinner could be half as large.
