### ISSUE TITLE
Unmount from the file manager: Operation not permitted

### ISSUE THREAD

**Issue by vermaden** [helloSystem/hello#50]
Try adding that to /etc/sysctl.conf for a start:

% sysctl vfs.usermount 
vfs.usermount: 1

**Comment by probonopd** [comment]
Thanks @vermaden but we are actually already doing this:
https://github.com/helloSystem/ISO/search?q=vfs.usermount

**Comment by vermaden** [comment]
Ok.

**Comment by grahamperrin** [comment]
I might look at this during the Christmas break. 

In the meantime, has `fstat(1)` revealed anything of interest?

**Comment by probonopd** [comment]
Nothing I could name sense of. Your help will be highly appreciated.

**Comment by grahamperrin** [comment]
What's used to automate mounts?

Brief observations from tests yesterday: 

1. volumes of the boot device could be repeatedly ejected then re-mounted using the GUI
2 attempts to eject any subsequently auto-mounted volume failed through the GUI, with a (contrary) report that the thing was **not** mounted
3. attempts to unmount from the command line (I probably used `umount`) failed
4. after physically disconnecting then reconnecting the boot device, volumes that were previously ejectable (see point 1) were no longer ejectable. 

Boot device: 32 GB Kingston DataTraveler 3.0 PMAP s/n `C860008AE288BF4189030BBD` from a 13.0-CURRENT ISO (I can't recall which one).

**Comment by probonopd** [comment]
> What's used to automate mounts?

gfvs as used by pcmanfm-qt which Filer is currently based on

**Comment by grahamperrin** [comment]
Partly contrary to my previous comment … 

`sudo umount` commands succeed, even whilst the mount point is browsed by Filer: 

![image](https://user-images.githubusercontent.com/192271/103373024-ab701d00-4acb-11eb-9720-6bb515602dcc.png)

### sudo

`sudo launch Filer` is visually strange (no surprise): 

![image](https://user-images.githubusercontent.com/192271/103373227-423cd980-4acc-11eb-836c-0963204617dd.png)

– and the GUI disappears after opting to **Unmount**: 

![image](https://user-images.githubusercontent.com/192271/103373284-6ac4d380-4acc-11eb-8f04-aaa9f9a70ade.png)

– but the context menu command succeeds; it's no longer mounted.

**Comment by probonopd** [comment]
Why are you running hello twice?

**Comment by grahamperrin** [comment]
Peculiar behaviour with USB devices with VirtualBox 5.⋯ on FreeBSD. 

Prefer to use USB devices with a real computer. 

Ease of use of KDE Plasma for taking screenshots. So, screenshots of a remotely controlled helloSystem to which a USB device is attached :-)

**Comment by probonopd** [comment]
> Ease of use of KDE Plasma for taking screenshots

Is there something about KDE screenshots that we could learn for helloSystem?

**Comment by vermaden** [comment]
Also keep in mind that **umount -f** is actually useful on FreeBSD and really works (forceful unmounting).

On Linux everytime I used **umount -f** it just said again that filesystem is used and can not be unmounted.

If course I would first use 'plain' **umount** and only if it fails after some timeout only then use **umount -f** command.

**Comment by grahamperrin** [comment]
> … first use 'plain' **umount** and only if it fails after some timeout only then use **umount -f** command.

+1 

In Mac OS X, for the dialogue in which Apple sometimes named the open file(s) it's possible that **lsof(8)** was used. 

Recently at <https://lists.freebsd.org/pipermail/freebsd-current/2020-November/077701.html> @freqlabs wrote:

> Please be wary of lsof. I'm not sure it works on OpenZFS. The port reaches into `/usr/src` for zfs headers in locations that don't exist anymore to access kernel memory in `/dev/kmem` using structs that are different in OpenZFS. It is likely not building the ZFS support code on 13-current, and it is not expected to work on 12 with openzfs from ports, either.

https://www.freebsd.org/cgi/man.cgi?sektion=8&query=lsof#BUGS

I should discourage automated force.

**Comment by vermaden** [comment]
You do not need **lsof(8)** if you have **procstat(8)** - at least on FreeBSD.

**Comment by probonopd** [comment]
Is "Operation not permitted" an issue of files being open? (It sounds like only root may unmount?)

**Comment by grahamperrin** [comment]
> Is "Operation not permitted" an issue of files being open?

It can be, however re: https://github.com/helloSystem/hello/issues/50#issuecomment-752715895 

> (It sounds like only root may unmount?)

I found that a sudo run of Filer succeeded where a normal run failed. 

Without Filer: superuser privileges were not required to `umount`.

**Comment by grahamperrin** [comment]
pcmanfm-qt also fails when run normally.

**Comment by probonopd** [comment]
Now, this is strange. Because I have exactly one machine where it works as intended. (This installation started out as NomadBSD once but I have since changed it a lot.)

**Comment by probonopd** [comment]
`sudo chmod +s /sbin/umount` makes it work. Is that ok to do @vermaden?

**Comment by grahamperrin** [comment]
Now I'm curious, how did helloSystem find itself _without_ a setuid bit here?

![image](https://user-images.githubusercontent.com/192271/103432793-ccc12e00-4bdd-11eb-9485-bd3b2298b32b.png)

**Comment by vermaden** [comment]
> `sudo chmod +s /sbin/umount` makes it work. Is that ok to do @vermaden?

Yes, it will work if you are in the **wheel** group.

**Comment by probonopd** [comment]
Yes. Seems like we have a working solution then.
