### ISSUE TITLE
Usability Issues

### ISSUE THREAD

**Issue by bert003** [helloSystem/hello#500]
I know Hello is meant to be installed on real hardware but I cannot do so. Therefore I am using VirtualBox. However the below issues are not all related to using it in a virtual machine I guess:

- When you rescale the VirtualBox window, the menus at the top stop working. You click and nothing happens. 
- I couldn't find a link to a File Explorer. Maybe I did not search well.
- When you minimise a window, where do you find it?
- I clicked Qlipper and then selected File -> Quit. The top toolbar disappeared.
- At one point, the Trash icon on the Desktop, changed to trashcan.desktop (the actual filename)
- When you try to click on some software (I tried Audacity), it prompts that it needs to be downloaded, asks for a password (which I input) and then nothing happens.

@probonopd I mentioned multiple issues here. If you would like them to be separate, please let me know. I wrote them all at once since I encountered them now while using the system.

**Comment by probonopd** [comment]
> When you rescale the VirtualBox window, the menus at the top stop working. You click and nothing happens.

Please post a bug in https://github.com/helloSystem/ISO/issues with details on how to reproduce this, ideally with screenshots.

> I couldn't find a link to a File Explorer. Maybe I did not search well.

Why would one want to open a "File Explorer". This is a concept totally unknown to Mac users. You never open the Finder. You open folders. In other words, the helloSystem Filer is running all the time. And only one instance of it can run at a time. So it is unclear to me what you are looking for.

> When you minimise a window, where do you find it?

In the top-right menu that has the icon of the frontmost application. This menu is where you can choose the other windows, including minimized ones.

> I clicked Qlipper and then selected File -> Quit. The top toolbar disappeared.

The "top toolbar" is the Menu, and the Menu should never disappear. If it does, it crashed. If you can reproduce it, then please open an issue for it in the Menu repository.

> At one point, the Trash icon on the Desktop, changed to trashcan.desktop (the actual filename)

If you can reproduce it, then please open an issue for it in the Filer repository.

> When you try to click on some software (I tried Audacity), it prompts that it needs to be downloaded, asks for a password (which I input) and then nothing happens.

This is a bug, if you can reproduce it, then please open an issue for it in the Utilities repository.

Let's continue discussion in the respective tickets.
