### ISSUE TITLE
Two small critiques regarding how this is advertised

### ISSUE THREAD

**Issue by time-killer-games** [helloSystem/hello#505]
"Less, but better!" sounds like an oxymoron, or at least sounds a bit odd. While this is also an oxmoron, i think you meant the more commonly recognized phrase "less is more." or perhaps the more verbose version, "Less, but sometimes, less is more" as less is not always more. You want to convince them it is more, and saying "Less, but better!" is it saying "Less, but better than less?" or is it really implying "Less, but better than alternatives?" This is very unclear by the choice of words.

The other critique being, and this is the only other thing i can think of for the time being: You say in the readme you need super user privileges to run apps that are not code signed or notarized, on macOS, but this is not so. 

https://derflounder.wordpress.com/2012/11/20/clearing-the-quarantine-extended-attribute-from-downloaded-applications/

Despite what the article above says, the command can have `sudo` ommitted completely and still remove the quarantine attribute. I've tested on macOS Ventura (Intel-based) on my late 2018 Mac Mini, and other people I've had confirm it also does work on the M1 and M2 Macs. Try it yourself if you have any doubts:

```
xattr -r -d com.apple.quarantine /path/to/MyApp.app
```

**Comment by probonopd** [comment]
> "Less, but better!" is actually a term coined by and a reference to [Dieter Rams](https://en.wikipedia.org/wiki/Dieter_Rams) who, at least in my opinion, showed that less can be better indeed.

> You say in the readme you need super user privileges to run apps that are not code signed or notarized, on macOS, but this is not so.

Thanks for the info, Where exactly did you see the wrong statement?

**Comment by time-killer-games** [comment]
#Because we want to run apps from "unidentified developers" that need no blessing by the operating system vendor and no workarounds like https://lapcatsoftware.com/articles/textedit-gatekeeper.html (Note: Maybe sudo spctl --master-disable does the trick if you are root on the machine, which means no luck on "managed" devices)

**Comment by time-killer-games** [comment]
I REALLY love your work btw! this OS and appimages are freaking awesome and this project is coming along very nicely with a lot of serious potential. :D

**Comment by time-killer-games** [comment]
a little off topic, do you have some other means you'd prefer to stay in touch if you would like me to contribute? I like discord and slack in particular. Not really a fan of mailing lists or IRC chats. I am attempting to write a FreeBSD based OS myself and the goal is to be a 100% permissive and complete desktop OS with an ImGui based desktop environment written from scratch (granted) it would probably be better to not reinvent the wheel and instead hop on someone else's development train.

**Comment by probonopd** [comment]
So, you are sure that `spctl --master-disable` (wothout `sudo`) does the trick?

**Comment by probonopd** [comment]
> a little off topic, do you have some other means you'd prefer to stay in touch if you would like me to contribute? 

https://hellosystem.github.io/docs/developer/contact.html

**Comment by time-killer-games** [comment]
> So, you are sure that `spctl --master-disable` (wothout `sudo`) does the trick?

that does need sudo, but what you said makes it look like that is your only option and there is no way to do it without super user.

This is what you'd do for the case of non-privileged users:

```
xattr -r -d com.apple.quarantine /path/to/MyApp.app
```

as mentioned previously.
