### ISSUE TITLE
Support iBus or other input in systems

### ISSUE THREAD

**Issue by louies0623** [helloSystem/hello#507]
### Discussed in https://github.com/helloSystem/hello/discussions/501

<div type='discussions-op-text'>

> <sup>Originally posted by **DavidLiang1129** May  9, 2023</sup>
Hello, everyone, I come from China. I installed hellosystem 0.8.1 on my Sony VAIO VPCCA16EC laptop some time ago. All the hardware except the camera works well. Thanks to all the contributors for their hard work! However, I found that although it has Chinese support, it still cannot input Chinese, which causes a certain degree of use barriers for Chinese users including me. On Linux system, I have heard of iBus, but I know hellosystem is based on FreeBSD, so I would like to ask, Does hellosystem support iBus or other input system? Thanks!![IMG_20230326_131950.jpg](https://user-images.githubusercontent.com/118408976/237055659-6051becf-2421-4b5d-9d1f-aabc68bed668.jpg)</div>

**Comment by probonopd** [comment]
Please continue the existing discussion in https://github.com/helloSystem/docs/issues/34.
