### ISSUE TITLE
Zip is still blank

### ISSUE THREAD

**Issue by louies0623** [helloSystem/hello#508]
[PC-1-screen0.webm](https://github.com/helloSystem/hello/assets/44593430/ce06d24d-5a03-4741-a46c-ebef981d3085)

**Comment by probonopd** [comment]
Cannot reproduce.

When the blank window opens, press Command-Shift-R to reload the contents of the window. Does that work?

**Comment by louies0623** [comment]
No work .Build: 0h352

**Comment by probonopd** [comment]
Please check if it has been mounted using the Terminal.

**Comment by probonopd** [comment]
On the Terminal, please run

```
mountarchive /path/to/your.zip
```

and watch for errors. Thanks! Do you get an error about libstdc++?

**Comment by probonopd** [comment]
In this case, `sudo pkg install gcc` and see if that makes it work.

**Comment by probonopd** [comment]
Looks like we are using libc++ in other places, but not for `mountarchive`. Reasons unclear at the moment; most likely because it was built with gcc rather than with clang.

**Comment by louies0623** [comment]
OH366 This version has been fixed.
