### ISSUE TITLE
open window effect

### ISSUE THREAD

**Issue by louies0623** [helloSystem/hello#511]
The previous hello system has a window effect that slides from top to bottom or fades in, but it is ugly. If change it to a Mac or windows11 window to open the special effect, it is boring and overwhelming. If possible, can change it to this.

https://github.com/helloSystem/hello/assets/44593430/d25542a1-ad8a-4dce-8362-8c81445ecd87

**Comment by probonopd** [comment]
I don't know how to do this and am fine with the current fade in/fade out animation. In the future, a fade-and-zoom animation would be preferred.

**Comment by flurick** [comment]
I recalled that the KDE/plasma desktop has some setting for theses kinds of effects, so I tried installing that system-settings package in a hello VM. Some effects worked, however when trying to install one of the open/close window animations (for example https://store.kde.org/p/1915781) it did not seem to install/activate. 

Perhaps theses kinds of kwin effects need some tweaks to be enabled in a possible future
