### ISSUE TITLE
Hello finder - Show folder tree in sidebar

### ISSUE THREAD

**Issue by louies0623** [helloSystem/hello#537]
![images (69)](https://github.com/helloSystem/hello/assets/44593430/8be35a41-7db5-4391-bd3a-3a6acd1421db)

![image](https://github.com/helloSystem/hello/assets/44593430/8c5a36f6-d933-4d0c-924a-9a668b1e7a68)

I hope it has a tree column like the picture to show the location of the folder, because sometimes there are different hard disks with the same folder name, and I don’t know which one it is, and then there is a button on it to view Or return to all levels of the current folder.

**Comment by probonopd** [comment]
Thanks for the suggestion @louies0623, but this is not planned as it is Windows-ish rather than Mac-like.

We are (loosely) following the published recommendations from
https://dl.acm.org/doi/book/10.5555/573097
