### ISSUE TITLE
EeePC R105D: When using battery, the screen does not display or light up after the startup screen.

### ISSUE THREAD

**Issue by louies0623** [helloSystem/hello#542]
When using a battery with about 50% charge, the screen does not display or light up after the startup screen ends.
![20230908_070947](https://github.com/helloSystem/hello/assets/44593430/acc0c102-0524-41c5-ad30-64bd9f0f2520)

**Comment by probonopd** [comment]
Please test with GhostBSD or NomadBSD. Does it work better there?

**Comment by louies0623** [comment]
Yes, it works on NomadBSD, but with the latest build 0I42 I can't reproduce it at the moment, so I'll just leave it at that and not sure if that bug still exists.
