### ISSUE TITLE
Localization of helloSystem

### ISSUE THREAD

**Issue by DaniloNegrilo** [helloSystem/hello#545]
helloSystem has been one of the best systems I have used and I want to increase the list of people who use it. And as much language support as possible in the system can help with this. I speak Ukrainian and I can help you translate helloSystem into Ukrainian.

**Comment by probonopd** [comment]
Hello @DaniloNegrilo. Glad you like helloSystem. Localization for helloSytem happens in https://hosted.weblate.org/projects/hellosystem/. Please have a look there. Thanks for your contribution.
