### ISSUE TITLE
When the Live CD displays the language menu, the USB driver has to wait several seconds before it can be used.

### ISSUE THREAD

**Issue by louies0623** [helloSystem/hello#546]
When the language menu is displayed, the mouse cannot be moved. The mouse must be slowed down for several seconds before it can be used normally, or it must be reinserted before it can be used immediately.

**Comment by probonopd** [comment]
The mouse driver is still being loaded at that time. Just wait a few seconds.

**Comment by louies0623** [comment]
On some devices, it took almost a minute to load but there was no response, and the USB had to be plugged in again.

**Comment by probonopd** [comment]
No, we modified the boot oder sequence for the Live ISO so that the graphical display appears earlier while other parts of the system are still being booted.

**Comment by louies0623** [comment]
I recently encountered a bug. After waiting for more than two minutes, it was unable to move the mouse or use the keyboard.
