### ISSUE TITLE
After ending the Bootsplash logo, immediately on the grid and mouse screen, use the trackpad to move the mouse and the computer will restart.

### ISSUE THREAD

**Issue by louies0623** [helloSystem/hello#548]
On the grid and mouse screen, the computer will restart after moving the mouse quickly with the trackpad.

build :0I42  ,installed
acer aspire one happy 2

**Comment by probonopd** [comment]
Moving the mouse _slowly_ with the trackpad works without crash?

**Comment by louies0623** [comment]
> Moving the mouse slowly with the trackpad works without crash?
 Yes, is crash.

> Is it working better in GhostBSD?
I can't test on it, but it works fine on NomadBSD.

**Comment by probonopd** [comment]
With hardware bugs, I cannot really help to debug this I don't the hardware.
Please try to find out what is different on the two systems, and experiment by making the setting on helloSystem more like on the system where it is working (e.g., NomadBSD). Once you know what needs to be changed in helloSystem, I can make the change.

Thanks!

**Comment by louies0623** [comment]
I think I can turn it off temporarily and wait until someone starts to respond and turn it on again, because my laptop is no longer here with me.
