### ISSUE TITLE
Undo translation vandalism

### ISSUE THREAD

**Issue by GranPC** [helloSystem/hello#558]
An user on Weblate has recently submitted vandalized translations to the Ubuntu translation project, resulting in the official Ubuntu 23.10 image being pulled: https://discourse.ubuntu.com/t/announcement-ubuntu-desktop-23-10-release-image-is-being-updated-to-resolve-a-malicious-translation-incident/39365

The user in question also happens to have submitted translations to this project, and later, reverted some of them from another account:

- https://hosted.weblate.org/user/DaniloNegrilo/#changes
- https://hosted.weblate.org/user/DaniloPidaras/#changes

Looking through their submitted strings, some of them also seem to contain inappropriate content:

![image](https://github.com/helloSystem/hello/assets/1385480/c0885901-a49b-481c-81f2-d133590f2a0c)

Out of an abundance of caution, even seeing that the user has voluntarily reverted some changes, I would probably nuke every change they have submitted and block them from contributing to the project.

**Comment by webknjaz** [comment]
Interestingly, they even have offensive words in the usernames. Also, note that even many of the seemingly legitimate entries are evidently auto-generated by some translation software and either have grammar or context mistakes.

**Comment by probonopd** [comment]
Thanks for bringing this to our attention. I have blocked that user and have set additional restrictions on the Ukrainian translation to make this type of behavior more difficult in the future.

As of today, do you still see offending translations? If yes, we'd need to find a way to revert all submissions of those users.

**Comment by probonopd** [comment]
Reverted. Hopefully I caught everything. Thanks for bringing this to our attention.
