### ISSUE TITLE
(meta) sleep and wake (suspend and resume)

### ISSUE THREAD

**Issue by grahamperrin** [helloSystem/hello#72]
Placeholder for links from issues elsewhere.

**Comment by dbisping** [comment]
Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. 

O the joy of my spirit - it is uncaged - it darts like lightning!
It is not enough to have this globe or a certain time,
I will have thousands of globes and all time.

- Walt Whitman
