### ISSUE TITLE
Imagine a system without – or with less reliance upon – a dock

### ISSUE THREAD

**Issue by grahamperrin** [helloSystem/hello#74]
Parallel to https://github.com/helloSystem/hello/issues/20 

For the past week (since watching [A quick look at helloSystem as of Xmas 2020](https://www.youtube.com/watch?v=PlPTVbhrKYM)) I've been thinking about the Mac OS tradition of:

* **top left** as a starting point
* with menus dropping **down**

– and the knowledge that 'average' users rarely or never paid attention to status bars (stuff at, or near, the foot of windows). 

When the **Dock** appeared with Mac OS X it certainly served a purpose, and no doubt its default position (foot of the screen) made the system more attractive to potential 'switchers' from Windows, however there began **a mixture** of menus that drop _down_ and menus that pop _up_. Then screens became wider, and extended desktops (dual widescreen) are increasingly commonplace, but there remains a Dock-at-the-bottom mentality – in many cases where it's: 

* essentially/potentially a waste of space; and
* not great, ergonomically.

Keeping this opening post brief, food for thought, Apple's **Application Switcher** and **Control Strip**: 

![image](https://user-images.githubusercontent.com/192271/103416449-c51e6c80-4b7e-11eb-9b87-38701dcf5b82.png)

![image](https://user-images.githubusercontent.com/192271/103416478-df584a80-4b7e-11eb-993c-a1331f2d00e8.png)

![image](https://user-images.githubusercontent.com/192271/103416464-d6677900-4b7e-11eb-9f39-4caa88cd0688.png)

– and https://github.com/helloSystem/Menu/issues/21 _Bring features from the Dock into the menu_.

Application Switcher was, in my experience, more useful than the Dock. If I recall correctly a double-click on its title bar would leave just the bar; there was drag-and-drop capability; and so on. 

### Image sources

[AppSwitcher Control](http://www.pascal.com/software/appswitcher/)

[Control Strip - Mac OS 9: Visual QuickStart Guide [Book]](https://www.oreilly.com/library/view/mac-os-9/0201700042/0201700042_ch14lev1sec5.html)

[Simple Beep – e37 – The Control Strip](https://simplebeep.com/podcast/e37-the-control-strip)

**Comment by probonopd** [comment]
Fully agree with

> Imagine a system without – or with less reliance upon – a dock

The Dock still feels a bit "alien" to me. It was not part of the classic System. And it wastes screen real estate. I think we should make it entirely optional.

Here is my take on the same issue, wdyt?
https://github.com/helloSystem/Menu/issues/21

**Comment by grahamperrin** [comment]
https://github.com/helloSystem/Menu/issues/21#issuecomment-753286182 – shared thinking; no need for this issue to be separate.
