### ISSUE TITLE
(VirtualBox) When a keyboard is (for example) 'unknown AT Keyboard', the Keyboard application should start automatically

### ISSUE THREAD

**Issue by grahamperrin** [helloSystem/hello#93]
https://bsd-hardware.info/index.php?id=ps/2:keyboard

    ID ps/2:keyboard
    Type input/keyboard
    Vendor  unknown
    Name AT Keyboard

– linked from a probe that was performed whilst using `hello-0.3.0_0C155-FreeBSD-12.1-amd64.iso` in a virtual machine. 

Truly, the at the time of writing it's a _Hewlett-Packard Slim Keyboard_ https://bsd-hardware.info/index.php?id=usb:03f0-354a but I expect to use a different keyboard in due course. 

----

See also: https://github.com/helloSystem/hello/issues/8

**Comment by probonopd** [comment]
Please always give tickets speaking titles. What needs to happen so that this ticket can be closed?

**Comment by dbisping** [comment]
Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. Unsubscribe. 

O the joy of my spirit - it is uncaged - it darts like lightning!
It is not enough to have this globe or a certain time,
I will have thousands of globes and all time.

- Walt Whitman
