### ISSUE TITLE
launchd  for mac ,how about hello system?

### ISSUE THREAD

**Issue by netroby** [helloSystem/hello#99]
Did the hello system has the launchd  ? the boot manager for mac

**Comment by probonopd** [comment]
No, helloSystem does not use `launchd`. It uses [FreeBSD `rc.d` scripts](https://www.freebsd.org/cgi/man.cgi?query=rc.d&sektion=8&n=1).

There was a project called ["NextBSD"](https://en.wikipedia.org/wiki/NextBSD) that had ported `launchd` to FreeBSD but the project seems not to be active anymore.
